#pragma once

namespace RayEffectsComputeShaders
{
inline constexpr const char* EffectsBeforePointLight = R"GLSL(#version 430 core
layout(local_size_x=8,local_size_y=8,local_size_z=1)in;
layout(rgba16f,binding=0)uniform writeonly image2D oShadowedDirect;
layout(rgba16f,binding=1)uniform writeonly image2D oGIRadiance;
layout(rgba16f,binding=2)uniform writeonly image2D oOpticalContribution;
layout(std430,binding=0)readonly buffer Triangles{vec4 triangles[];};
layout(std430,binding=1)readonly buffer BLASNodes{vec4 blasNodes[];};
layout(std430,binding=2)readonly buffer BLASIndices{float blasIndices[];};
layout(std430,binding=3)readonly buffer Instances{vec4 instances[];};
layout(std430,binding=4)readonly buffer TLASNodes{vec4 tlasNodes[];};
layout(std430,binding=5)readonly buffer TLASIndices{float tlasIndices[];};
layout(std430,binding=6)readonly buffer InstanceIdentities{uvec4 instanceIdentities[];};
layout(std430,binding=7)readonly buffer Materials{vec4 materials[];};
uniform sampler2D uPositionCoverage,uGeometricNormal,uShadingNormalModel,uAlbedoShininess,uSpecularMirror,uUnshadowedDirect,uSky;
uniform usampler2D uIdentity;uniform sampler2DArray uMaterialAtlas;
uniform bool uDoShadows,uDoGI,uDoReflections,uDoTranslucency,uHasSky;uniform ivec2 uOutputSize;
uniform int uInstanceCount,uGISamples,uGIBounces,uShadowSamples,uPrimaryOpticsBase,uPrimaryMaterialCount,uFrameIndex;
uniform float uGIStrength,uReflectionStrength,uShadowSoftness,uSkyExponent;
uniform vec3 uEye,uEnvironmentTint,uSkyHorizon,uSkyZenith;
const int MAX_LIGHTS=16;uniform int uLightCount;uniform vec3 uLightPositions[MAX_LIGHTS],uLightSources[MAX_LIGHTS];
vec3 sky(vec3 d){d=normalize(d);if(uHasSky){float u=atan(d.z,d.x)*.1591549431+.5,v=asin(clamp(d.y,-1.,1.))*.3183098862+.5;return textureLod(uSky,vec2(u,v),0.).rgb*uEnvironmentTint;}float k=pow(clamp(d.y*.5+.5,0.,1.),max(uSkyExponent,.01));return mix(uSkyHorizon,uSkyZenith,k)*uEnvironmentTint;}
vec4 ir0(int i){return instances[i*7];}vec4 ir1(int i){return instances[i*7+1];}vec4 ir2(int i){return instances[i*7+2];}vec4 ioff(int i){return instances[i*7+4];}vec3 imin(int i){return instances[i*7+5].xyz;}bool iclosed(int i){return instances[i*7+5].w>.5;}vec3 imax(int i){return instances[i*7+6].xyz;}uvec4 iid(int i){return instanceIdentities[i];}vec4 tt(int t,int x){return triangles[t*7+x];}vec3 tp(int t,int c){return tt(t,c).xyz;}
int mi(int i,int t){uvec4 q=iid(i);uint s=q.w!=0u?0u:floatBitsToUint(tt(t,6).x);if(s>=q.z)s=0u;return int(q.y+s);}uint mid(int i,int t){return floatBitsToUint(materials[mi(i,t)*8+2].w);}vec4 po(uint id,int x){if(id==0u||id>uint(uPrimaryMaterialCount))return x==0?vec4(1,1,1,1):vec4(1.52,1,0,1);return materials[uPrimaryOpticsBase+(int(id)-1)*2+x];}vec4 so(int m,int x){return materials[m*8+6+x];}
vec3 xp(vec4 a,vec4 b,vec4 c,vec3 p){return vec3(dot(a.xyz,p)+a.w,dot(b.xyz,p)+b.w,dot(c.xyz,p)+c.w);}vec3 xd(vec4 a,vec4 b,vec4 c,vec3 d){return vec3(dot(a.xyz,d),dot(b.xyz,d),dot(c.xyz,d));}vec3 xn(vec4 a,vec4 b,vec4 c,vec3 n){return normalize(vec3(a.x*n.x+b.x*n.y+c.x*n.z,a.y*n.x+b.y*n.y+c.y*n.z,a.z*n.x+b.z*n.y+c.z*n.z));}
bool slab(vec3 ro,vec3 rd,vec3 mn,vec3 mx,float mt){vec3 s=vec3(abs(rd.x)<1e-8?(rd.x<0.?-1e-8:1e-8):rd.x,abs(rd.y)<1e-8?(rd.y<0.?-1e-8:1e-8):rd.y,abs(rd.z)<1e-8?(rd.z<0.?-1e-8:1e-8):rd.z);vec3 a=(mn-ro)/s,b=(mx-ro)/s,en=min(a,b),ex=max(a,b);return max(max(en.x,en.y),max(en.z,0.))<=min(min(ex.x,ex.y),min(ex.z,mt));}
bool th(vec3 ro,vec3 rd,vec3 a,vec3 b,vec3 c,float mn,inout float cl,out vec2 uv){vec3 e1=b-a,e2=c-a,p=cross(rd,e2);float det=dot(e1,p);if(abs(det)<1e-8)return false;vec3 s=ro-a;float iv=1./det,u=dot(s,p)*iv;if(u<0.||u>1.)return false;vec3 q=cross(s,e1);float v=dot(rd,q)*iv,t=dot(e2,q)*iv;if(v<0.||u+v>1.||t<=mn||t>=cl)return false;cl=t;uv=vec2(u,v);return true;}
bool blas(int ins,vec3 wo,vec3 wd,float mn,uint oo,uint om,inout float cl,out int ot,out vec2 ob){vec4 a0=ir0(ins),a1=ir1(ins),a2=ir2(ins),of=ioff(ins);vec3 ro=xp(a0,a1,a2,wo),rd=xd(a0,a1,a2,wd);int nb=int(of.x+.5),tb=int(of.y+.5),ib=int(of.z+.5),st[64],sp=0;st[sp++]=0;bool hit=false;while(sp>0){int n=st[--sp];vec4 a=blasNodes[(nb+n)*2],b=blasNodes[(nb+n)*2+1];if(!slab(ro,rd,a.xyz,b.xyz,cl))continue;int cnt=int(b.w);if(cnt>0){int start=int(a.w);for(int k=0;k<cnt;++k){int tr=tb+int(blasIndices[ib+start+k]+.5);float c=cl;vec2 ba;if(th(ro,rd,tp(tr,0),tp(tr,1),tp(tr,2),mn,c,ba)){uint m=mid(ins,tr);if(iid(ins).x==oo&&m==om&&c<=mn*4.)continue;cl=c;ot=tr;ob=ba;hit=true;}}}else if(sp<=62){st[sp++]=int(a.w);st[sp++]=-cnt;}}return hit;}
bool trace(vec3 ro,vec3 rd,float mn,float mx,uint oo,uint om,out float ht,out int hi,out int htr,out vec2 hb){ht=mx;hi=-1;htr=-1;if(uInstanceCount<=0)return false;int st[32],sp=0;st[sp++]=0;while(sp>0){int n=st[--sp];vec4 a=tlasNodes[n*2],b=tlasNodes[n*2+1];if(!slab(ro,rd,a.xyz,b.xyz,ht))continue;int cnt=int(b.w);if(cnt>0){int start=int(a.w);for(int k=0;k<cnt;++k){int ins=int(tlasIndices[start+k]+.5);if(!slab(ro,rd,imin(ins),imax(ins),ht))continue;float c=ht;int tr;vec2 ba;if(blas(ins,ro,rd,mn,oo,om,c,tr,ba)&&c<ht){ht=c;hi=ins;htr=tr;hb=ba;}}}else if(sp<=30){st[sp++]=int(a.w);st[sp++]=-cnt;}}return hi>=0;}
vec3 alb(int i,int t,vec2 b){int m=mi(i,t);vec3 base=materials[m*8].rgb;vec4 el=materials[m*8+3],meta=materials[m*8+4];if(el.w<0.)return base;float w=1.-b.x-b.y;vec2 uv=vec2(tt(t,0).w,tt(t,3).w)*w+vec2(tt(t,1).w,tt(t,4).w)*b.x+vec2(tt(t,2).w,tt(t,5).w)*b.y;uv*=meta.xy;uv=meta.z>.5?fract(uv):clamp(uv,vec2(0),vec2(1));vec2 logical=materials[m*8+5].xy,atlas=vec2(textureSize(uMaterialAtlas,0).xy);vec2 atlasUV=(uv*logical+vec2(1.))/atlas;vec3 decoded=pow(max(texture(uMaterialAtlas,vec3(atlasUV,el.w)).rgb,vec3(0)),vec3(2.2));return base*decoded;}
void surface(int i,int t,vec2 b,out vec3 n,out vec3 a,out vec3 am,out vec3 sp,out float sh,out vec3 em,out uint id){float w=1.-b.x-b.y;vec3 ln=normalize(tt(t,3).xyz*w+tt(t,4).xyz*b.x+tt(t,5).xyz*b.y);n=xn(ir0(i),ir1(i),ir2(i),ln);int m=mi(i,t);a=alb(i,t,b);am=materials[m*8+1].rgb;sh=materials[m*8+1].a;sp=materials[m*8+2].rgb;em=materials[m*8+3].rgb;id=mid(i,t);}
float h(vec2 x){x+=vec2(float(uFrameIndex)*17.17,float(uFrameIndex)*43.31);return fract(sin(dot(x,vec2(127.1,311.7)))*43758.5453);}void basis(vec3 n,out vec3 t,out vec3 b){vec3 u=abs(n.y)<.99?vec3(0,1,0):vec3(1,0,0);t=normalize(cross(u,n));b=cross(n,t);}vec3 hemi(vec3 n,float a,float b){float r=sqrt(a),p=6.2831853*b;vec3 t,bt;basis(n,t,bt);return normalize(t*r*cos(p)+bt*r*sin(p)+n*sqrt(max(0.,1.-a)));}
)GLSL";
inline constexpr const char* EffectsAfterPointLight = R"GLSL(
vec3 direct(vec3 p,vec3 n,vec3 v,vec3 a,vec3 sp,float sh){vec3 z=vec3(0);for(int i=0;i<MAX_LIGHTS;++i){if(i>=uLightCount)break;vec3 df,ss;evaluatePointLight(p,n,v,a,sp,sh,uLightPositions[i],uLightSources[i],df,ss);z+=df+ss;}return z;}
vec3 shadeRay(vec3 ro,vec3 rd,float ep,uint oo,uint om){float ht;int hi,tr;vec2 ba;if(!trace(ro,rd,ep,1e20,oo,om,ht,hi,tr,ba))return sky(rd);vec3 n,a,am,sp,em;float sh;uint id;surface(hi,tr,ba,n,a,am,sp,sh,em,id);return em+am*a+direct(ro+rd*ht,n,normalize(-rd),a,sp,sh);}
float fres(float c,float a,float b){float r=(a-b)/(a+b),f=r*r,q=1.-clamp(c,0.,1.);return f+(1.-f)*q*q*q*q*q;}vec3 beer(vec3 c,float refd,float d){vec3 s=-log(clamp(c,vec3(.0001),vec3(1)))/max(refd,.0001);return exp(-s*max(d,0.));}int findIns(uint id){for(int i=0;i<uInstanceCount;++i)if(iid(i).x==id)return i;return -1;}
vec3 glassRay(vec3 p,vec3 I,vec3 n,float ep,uvec2 ids,vec4 p0,vec4 p1,vec3 reflected){vec3 en=dot(I,n)<0.?n:-n;float F=fres(dot(-I,en),1.,p1.x);vec3 inside=refract(I,en,1./max(p1.x,1.));if(dot(inside,inside)<1e-8)return reflected;int ins=findIns(ids.x);if(ins<0||!iclosed(ins))return reflected;float xt=1e20;int tr;vec2 ba;if(!blas(ins,p-en*ep,normalize(inside),ep,0u,0u,xt,tr,ba)||mid(ins,tr)!=ids.y)return reflected;vec3 xn0,a,am,sp,em;float sh;uint id;surface(ins,tr,ba,xn0,a,am,sp,sh,em,id);vec3 hp=p-en*ep+normalize(inside)*xt,exn=dot(inside,xn0)<0.?xn0:-xn0;vec3 outd=refract(normalize(inside),exn,max(p1.x,1.));if(dot(outd,outd)<1e-8)return reflected;vec3 transmitted=shadeRay(hp-exn*ep,normalize(outd),ep,ids.x,ids.y);return F*reflected+(1.-F)*beer(p0.rgb,p1.y,xt)*transmitted;}
vec3 shadowT(vec3 ro,vec3 rd,float ep,float dst,uint oo,uint om){vec3 throughput=vec3(1);bool crossed=false;vec3 origin=ro;float remain=dst;for(int step=0;step<12;++step){if(remain<=ep)return throughput;float ht;int hi,tr;vec2 ba;if(!trace(origin,rd,ep,remain-ep,oo,om,ht,hi,tr,ba))return throughput;int m=mi(hi,tr);vec4 q0=so(m,0),q1=so(m,1);if(q1.z<.5)return vec3(0);vec3 n,a,am,sp,em;float sh;uint id;surface(hi,tr,ba,n,a,am,sp,sh,em,id);if(q1.w<.5){float advance=ht+ep;origin+=rd*advance;remain-=advance;oo=0u;om=0u;continue;}if(crossed||!iclosed(hi))return vec3(0);vec3 hp=origin+rd*ht;float xt=remain-ht;int xtr;vec2 xb;if(!blas(hi,hp+rd*ep,rd,ep,0u,0u,xt,xtr,xb)||mid(hi,xtr)!=id)return vec3(0);throughput*=(1.-fres(abs(dot(-rd,n)),1.,q1.x))*beer(q0.rgb,q1.y,xt);float advance=ht+ep+xt;origin+=rd*advance;remain-=advance;oo=0u;om=0u;crossed=true;}return vec3(0);}
void main(){ivec2 px=ivec2(gl_GlobalInvocationID.xy);if(any(greaterThanEqual(px,uOutputSize)))return;vec2 uv=(vec2(px)+vec2(.5))/vec2(uOutputSize);vec2 fc=vec2(px)+vec2(.5);if(uDoShadows)imageStore(oShadowedDirect,px,vec4(0,0,0,1));if(uDoGI)imageStore(oGIRadiance,px,vec4(0));if(uDoReflections||uDoTranslucency)imageStore(oOpticalContribution,px,vec4(0,0,0,1));vec4 pc=texture(uPositionCoverage,uv);if(pc.a<=.5)return;vec3 p=pc.xyz;vec4 nm=texture(uShadingNormalModel,uv);vec3 sn=normalize(nm.xyz),gn=normalize(texture(uGeometricNormal,uv).xyz);int model=int(nm.w+.5);vec4 ash=texture(uAlbedoShininess,uv),sm=texture(uSpecularMirror,uv);vec3 pa=ash.rgb;float mir=sm.a;uvec2 ids=texture(uIdentity,uv).rg;float ep=.0015+.001*length(p-uEye);vec3 org=p+gn*ep;
if(uDoShadows){vec3 unshadowed=vec3(0),shadowed=vec3(0),v=normalize(uEye-p);for(int l=0;l<MAX_LIGHTS;++l){if(l>=uLightCount)break;vec3 to=uLightPositions[l]-p;float dst=length(to);if(dst<=1e-5)continue;vec3 df,ss;evaluatePointLight(p,sn,v,pa,sm.rgb,ash.a,uLightPositions[l],uLightSources[l],df,ss);vec3 contribution=df+ss;unshadowed+=contribution;vec3 d=to/dst,t,b;basis(d,t,b);vec3 visible=vec3(0);for(int s=0;s<16;++s){if(s>=uShadowSamples)break;vec2 seed=fc+vec2(float(l)*37.17+float(s)*11.73,float(l)*19.31+float(s)*7.91);float a=h(seed),q=h(seed.yx+vec2(13.1,29.7));vec3 jd=normalize(d+(t*cos(6.2831853*q)+b*sin(6.2831853*q))*uShadowSoftness*sqrt(a));visible+=shadowT(org,jd,ep,dst,ids.x,ids.y);}shadowed+=contribution*(visible/float(uShadowSamples));}if(model==2)imageStore(oShadowedDirect,px,vec4(shadowed,1));else{vec3 ratio=vec3(1);if(unshadowed.r!=0.)ratio.r=shadowed.r/max(unshadowed.r,1e-5);if(unshadowed.g!=0.)ratio.g=shadowed.g/max(unshadowed.g,1e-5);if(unshadowed.b!=0.)ratio.b=shadowed.b/max(unshadowed.b,1e-5);imageStore(oShadowedDirect,px,vec4(texture(uUnshadowedDirect,uv).rgb*clamp(ratio,vec3(0),vec3(1)),1));}}
if(uDoGI&&uGISamples>0){vec3 g=vec3(0);for(int s=0;s<32;++s){if(s>=uGISamples)break;vec3 ro=org,rd=hemi(gn,h(fc+vec2(float(s)*1.7,.13)),h(fc.yx+vec2(float(s)*2.3,.71))),through=pa;uint oo=ids.x,om=ids.y;if(uGIBounces==0){float ht;int hi,tr;vec2 ba;if(!trace(ro,rd,ep,1e20,oo,om,ht,hi,tr,ba))g+=through*sky(rd);continue;}for(int bn=0;bn<4;++bn){if(bn>=uGIBounces)break;float ht;int hi,tr;vec2 ba;if(!trace(ro,rd,ep,1e20,oo,om,ht,hi,tr,ba)){g+=through*sky(rd);break;}vec3 n,a,am,sp,em;float sh;uint id;surface(hi,tr,ba,n,a,am,sp,sh,em,id);vec3 hp=ro+rd*ht;g+=through*(em+am*a+direct(hp,n,normalize(-rd),a,sp,sh));through*=a;ro=hp+n*ep;rd=hemi(n,h(fc+vec2(float(s*11+bn),.37)),h(fc.yx+vec2(float(s*13),float(bn)+.61)));oo=iid(hi).x;om=id;}}imageStore(oGIRadiance,px,vec4(g*(uGIStrength/float(uGISamples)),1));}
vec4 p0=po(ids.y,0),p1=po(ids.y,1);float kt=uDoTranslucency&&p1.z>.5?1.-clamp(p0.a,0.,1.):0.;float kr=(1.-kt)*(uDoReflections?clamp(mir*uReflectionStrength,0.,1.):0.);float kl=1.-kt-kr;vec3 I=normalize(p-uEye),rd=normalize(reflect(I,sn));vec3 reflected=(kr>0.||kt>0.)?shadeRay(org,rd,ep,ids.x,ids.y):vec3(0);vec3 glass=kt>0.?glassRay(p,I,sn,ep,ids,p0,p1,reflected):vec3(0);imageStore(oOpticalContribution,px,vec4(kr*reflected+kt*glass,kl));}
)GLSL";
} // namespace RayEffectsComputeShaders
