#pragma once
namespace RayEffectsFragmentShaders {
inline constexpr const char* FullscreenVertex=R"GLSL(#version 330 core
out vec2 vUV;void main(){vec2 p=vec2((gl_VertexID<<1)&2,gl_VertexID&2);vUV=p;gl_Position=vec4(p*2.0-1.0,0,1);}
)GLSL";
inline constexpr const char* EffectsFragment=R"GLSL(#version 330 core
in vec2 vUV;layout(location=0)out float oShadowVisibility;layout(location=1)out vec4 oGIRadiance;layout(location=2)out vec4 oReflectionRadiance;
uniform sampler2D uPositionCoverage,uGeometricNormal,uShadingNormalModel,uAlbedoShininess,uSpecularMirror,uSky;uniform usampler2D uIdentity;
uniform samplerBuffer uTriangles,uBLASNodes,uBLASIndices,uInstances,uTLASNodes,uTLASIndices,uMaterials;uniform usamplerBuffer uInstanceIdentities;uniform sampler2DArray uMaterialAtlas;
uniform bool uDoShadows,uDoGI,uDoReflections,uHasSky;uniform int uInstanceCount,uGISamples,uGIBounces,uShadowSamples;uniform float uGIStrength,uReflectionStrength,uShadowSoftness,uSkyExponent;uniform vec3 uEye,uEnvironmentTint,uSkyHorizon,uSkyZenith;
const int MAX_LIGHTS=16;uniform int uLightCount;uniform vec3 uLightPositions[MAX_LIGHTS],uLightRadiances[MAX_LIGHTS];
vec3 sky(vec3 d){d=normalize(d);if(uHasSky){float u=atan(d.z,d.x)*.1591549431+.5,v=asin(clamp(d.y,-1.,1.))*.3183098862+.5;return textureLod(uSky,vec2(u,v),0.).rgb*uEnvironmentTint;}float k=pow(clamp(d.y*.5+.5,0.,1.),max(uSkyExponent,.01));return mix(uSkyHorizon,uSkyZenith,k)*uEnvironmentTint;}
vec4 ir0(int i){return texelFetch(uInstances,i*7);}vec4 ir1(int i){return texelFetch(uInstances,i*7+1);}vec4 ir2(int i){return texelFetch(uInstances,i*7+2);}vec4 ioff(int i){return texelFetch(uInstances,i*7+4);}vec3 imin(int i){return texelFetch(uInstances,i*7+5).xyz;}vec3 imax(int i){return texelFetch(uInstances,i*7+6).xyz;}uvec4 iid(int i){return texelFetch(uInstanceIdentities,i);}vec4 tt(int t,int x){return texelFetch(uTriangles,t*7+x);}vec3 tp(int t,int c){return tt(t,c).xyz;}
int mi(int i,int t){uvec4 q=iid(i);uint s=q.w!=0u?0u:floatBitsToUint(tt(t,6).x);if(s>=q.z)s=0u;return int(q.y+s);}uint mid(int i,int t){return floatBitsToUint(texelFetch(uMaterials,mi(i,t)*6+2).w);}
vec3 xp(vec4 a,vec4 b,vec4 c,vec3 p){return vec3(dot(a.xyz,p)+a.w,dot(b.xyz,p)+b.w,dot(c.xyz,p)+c.w);}vec3 xd(vec4 a,vec4 b,vec4 c,vec3 d){return vec3(dot(a.xyz,d),dot(b.xyz,d),dot(c.xyz,d));}vec3 xn(vec4 a,vec4 b,vec4 c,vec3 n){return normalize(vec3(a.x*n.x+b.x*n.y+c.x*n.z,a.y*n.x+b.y*n.y+c.y*n.z,a.z*n.x+b.z*n.y+c.z*n.z));}
bool slab(vec3 ro,vec3 rd,vec3 mn,vec3 mx,float mt){vec3 s=vec3(abs(rd.x)<1e-8?(rd.x<0.?-1e-8:1e-8):rd.x,abs(rd.y)<1e-8?(rd.y<0.?-1e-8:1e-8):rd.y,abs(rd.z)<1e-8?(rd.z<0.?-1e-8:1e-8):rd.z);vec3 a=(mn-ro)/s,b=(mx-ro)/s,en=min(a,b),ex=max(a,b);return max(max(en.x,en.y),max(en.z,0.))<=min(min(ex.x,ex.y),min(ex.z,mt));}
bool th(vec3 ro,vec3 rd,vec3 a,vec3 b,vec3 c,float mn,inout float cl,out vec2 uv){vec3 e1=b-a,e2=c-a,p=cross(rd,e2);float det=dot(e1,p);if(abs(det)<1e-8)return false;vec3 s=ro-a;float iv=1./det,u=dot(s,p)*iv;if(u<0.||u>1.)return false;vec3 q=cross(s,e1);float v=dot(rd,q)*iv,t=dot(e2,q)*iv;if(v<0.||u+v>1.||t<=mn||t>=cl)return false;cl=t;uv=vec2(u,v);return true;}
bool blas(int ins,vec3 wo,vec3 wd,float mn,uint oo,uint om,inout float cl,out int ot,out vec2 ob){vec4 a0=ir0(ins),a1=ir1(ins),a2=ir2(ins),of=ioff(ins);vec3 ro=xp(a0,a1,a2,wo),rd=xd(a0,a1,a2,wd);int nb=int(of.x+.5),tb=int(of.y+.5),ib=int(of.z+.5),st[64],sp=0;st[sp++]=0;bool hit=false;while(sp>0){int n=st[--sp];vec4 a=texelFetch(uBLASNodes,(nb+n)*2),b=texelFetch(uBLASNodes,(nb+n)*2+1);if(!slab(ro,rd,a.xyz,b.xyz,cl))continue;int cnt=int(b.w);if(cnt>0){int start=int(a.w);for(int k=0;k<cnt;++k){int tr=tb+int(texelFetch(uBLASIndices,ib+start+k).x+.5);float c=cl;vec2 ba;if(th(ro,rd,tp(tr,0),tp(tr,1),tp(tr,2),mn,c,ba)){uint m=mid(ins,tr);if(iid(ins).x==oo&&m==om&&c<=mn*4.)continue;cl=c;ot=tr;ob=ba;hit=true;}}}else if(sp<=62){st[sp++]=int(a.w);st[sp++]=-cnt;}}return hit;}
bool trace(vec3 ro,vec3 rd,float mn,float mx,uint oo,uint om,out float ht,out int hi,out int htr,out vec2 hb){ht=mx;hi=-1;htr=-1;if(uInstanceCount<=0)return false;int st[32],sp=0;st[sp++]=0;while(sp>0){int n=st[--sp];vec4 a=texelFetch(uTLASNodes,n*2),b=texelFetch(uTLASNodes,n*2+1);if(!slab(ro,rd,a.xyz,b.xyz,ht))continue;int cnt=int(b.w);if(cnt>0){int start=int(a.w);for(int k=0;k<cnt;++k){int ins=int(texelFetch(uTLASIndices,start+k).x+.5);if(!slab(ro,rd,imin(ins),imax(ins),ht))continue;float c=ht;int tr;vec2 ba;if(blas(ins,ro,rd,mn,oo,om,c,tr,ba)&&c<ht){ht=c;hi=ins;htr=tr;hb=ba;}}}else if(sp<=30){st[sp++]=int(a.w);st[sp++]=-cnt;}}return hi>=0;}
vec3 alb(int i,int t,vec2 b){int m=mi(i,t);vec3 base=texelFetch(uMaterials,m*6).rgb;vec4 el=texelFetch(uMaterials,m*6+3),meta=texelFetch(uMaterials,m*6+4);if(el.w<0.)return base;float w=1.-b.x-b.y;vec2 uv=vec2(tt(t,0).w,tt(t,3).w)*w+vec2(tt(t,1).w,tt(t,4).w)*b.x+vec2(tt(t,2).w,tt(t,5).w)*b.y;uv*=meta.xy;uv=meta.z>.5?fract(uv):clamp(uv,vec2(0),vec2(1));vec2 logical=texelFetch(uMaterials,m*6+5).xy,atlas=vec2(textureSize(uMaterialAtlas,0).xy);vec2 atlasUV=(uv*logical+vec2(1.))/atlas;vec3 decoded=pow(max(texture(uMaterialAtlas,vec3(atlasUV,el.w)).rgb,vec3(0)),vec3(2.2));return base*decoded;}
void surface(int i,int t,vec2 b,out vec3 n,out vec3 a,out vec3 am,out vec3 em,out uint id){float w=1.-b.x-b.y;vec3 ln=normalize(tt(t,3).xyz*w+tt(t,4).xyz*b.x+tt(t,5).xyz*b.y);n=xn(ir0(i),ir1(i),ir2(i),ln);int m=mi(i,t);a=alb(i,t,b);am=texelFetch(uMaterials,m*6+1).rgb;em=texelFetch(uMaterials,m*6+3).rgb;id=mid(i,t);}
float h(vec2 x){return fract(sin(dot(x,vec2(127.1,311.7)))*43758.5453);}void basis(vec3 n,out vec3 t,out vec3 b){vec3 u=abs(n.y)<.99?vec3(0,1,0):vec3(1,0,0);t=normalize(cross(u,n));b=cross(n,t);}vec3 hemi(vec3 n,float a,float b){float r=sqrt(a),p=6.2831853*b;vec3 t,bt;basis(n,t,bt);return normalize(t*r*cos(p)+bt*r*sin(p)+n*sqrt(max(0.,1.-a)));}vec3 direct(vec3 p,vec3 n,vec3 a){vec3 z=vec3(0);for(int i=0;i<MAX_LIGHTS;++i){if(i>=uLightCount)break;vec3 d=uLightPositions[i]-p;float d2=max(dot(d,d),.01);z+=a*uLightRadiances[i]*max(dot(n,normalize(d)),0.)/d2;}return z;}
void main(){oShadowVisibility=1.;oGIRadiance=vec4(0);oReflectionRadiance=vec4(0);vec4 pc=texture(uPositionCoverage,vUV);if(pc.a<=.5)return;vec3 p=pc.xyz,gn=normalize(texture(uGeometricNormal,vUV).xyz),sn=normalize(texture(uShadingNormalModel,vUV).xyz),pa=texture(uAlbedoShininess,vUV).rgb;float mir=texture(uSpecularMirror,vUV).a;uvec2 ids=texture(uIdentity,vUV).rg;float ep=.0015+.001*length(p-uEye);vec3 org=p+gn*ep;
if(uDoShadows){float sum=0.;int rays=0;for(int l=0;l<MAX_LIGHTS;++l){if(l>=uLightCount)break;vec3 to=uLightPositions[l]-p;float dst=length(to);if(dst<=1e-5)continue;vec3 d=to/dst,t,b;basis(d,t,b);for(int s=0;s<16;++s){if(s>=uShadowSamples)break;float a=h(gl_FragCoord.xy+vec2(float(s*7+l),.31)),q=h(gl_FragCoord.yx+vec2(float(s*3),float(l)+.79));vec3 jd=normalize(d+(t*cos(6.2831853*q)+b*sin(6.2831853*q))*uShadowSoftness*sqrt(a));float ht;int hi,tr;vec2 ba;sum+=trace(org,jd,ep,dst-ep,ids.x,ids.y,ht,hi,tr,ba)?0.:1.;++rays;}}oShadowVisibility=rays>0?sum/float(rays):1.;}
if(uDoGI&&uGISamples>0){vec3 g=vec3(0);for(int s=0;s<32;++s){if(s>=uGISamples)break;vec3 ro=org,rd=hemi(gn,h(gl_FragCoord.xy+vec2(float(s)*1.7,.13)),h(gl_FragCoord.yx+vec2(float(s)*2.3,.71))),through=pa;uint oo=ids.x,om=ids.y;if(uGIBounces==0){float ht;int hi,tr;vec2 ba;if(!trace(ro,rd,ep,1e20,oo,om,ht,hi,tr,ba))g+=through*sky(rd);continue;}for(int bn=0;bn<4;++bn){if(bn>=uGIBounces)break;float ht;int hi,tr;vec2 ba;if(!trace(ro,rd,ep,1e20,oo,om,ht,hi,tr,ba)){g+=through*sky(rd);break;}vec3 n,a,am,em;uint id;surface(hi,tr,ba,n,a,am,em,id);vec3 hp=ro+rd*ht;g+=through*(em+am*a+direct(hp,n,a));through*=a;ro=hp+n*ep;rd=hemi(n,h(gl_FragCoord.xy+vec2(float(s*11+bn),.37)),h(gl_FragCoord.yx+vec2(float(s*13),float(bn)+.61)));oo=iid(hi).x;om=id;}}oGIRadiance=vec4(g*(uGIStrength/float(uGISamples)),1);}
if(uDoReflections&&mir>0.&&uReflectionStrength>0.){vec3 d=normalize(reflect(normalize(p-uEye),sn));float ht;int hi,tr;vec2 ba;vec3 z;if(trace(org,d,ep,1e20,ids.x,ids.y,ht,hi,tr,ba)){vec3 n,a,am,em;uint id;surface(hi,tr,ba,n,a,am,em,id);z=em+am*a+direct(org+d*ht,n,a)+a*sky(reflect(d,n))*.25;}else z=sky(d);oReflectionRadiance=vec4(z*mir*uReflectionStrength,1);}}
)GLSL";
}
