<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <!-- Output to the consuming solution's bin\ (project-local), not the engine's. -->
    <OutDir>$(SolutionDir)bin\</OutDir>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level3</WarningLevel>
      <LanguageStandard>stdcpp17</LanguageStandard>
      <AdditionalIncludeDirectories>
        $(EngineRootDir)include;
        $(EngineRootDir)Engine\Core;
        $(EngineRootDir)Engine\Mesh;
        $(EngineRootDir)Engine\Rasterizer;
        $(EngineRootDir)Engine\Framework;
        $(EngineRootDir)Engine\World;
        $(EngineRootDir)Engine\Light;
        $(EngineRootDir)Engine\Physics;
        $(EngineRootDir)Engine\Player;
        $(EngineRootDir)Engine\RayTracing;
        $(EngineRootDir)Engine\Render;
        $(EngineRootDir)Engine\Import;
        %(AdditionalIncludeDirectories)
      </AdditionalIncludeDirectories>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(EngineRootDir)lib;%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>glew32.lib;freeglut.lib;glfw3.lib;glfw3dll.lib;opengl32.lib;glu32.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>
