// GPU renderer headers (must come before any GLFW / gl.h inclusion)
#include <GL/glew.h>
#include <glm/gtc/type_ptr.hpp>
#include <iostream>
#include <string>
#include <map>
#include <set>
#include <random>
#include <cmath>
#include <sstream>

// Surface / light types used by the pass implementations
#include "SphereSurface.h"
#include "CubeSurface.h"
#include "PlaneSurface.h"
#include "../Light/PointLight.h"
#include "../Light/EnvironmentLight.h"

// Pass headers (declarations only — implementations are below)
#include "RenderConfig.h"
#include "GeometryPass.h"
#include "MaterialPass.h"
#include "DirectLightPass.h"
#include "IndirectLightPass.h"
#include "PostProcessPass.h"

#include "URayTracing.h"
#include "UScene.h"
#include "ACamera.h"
#include "AActor.h"
#include "../Light/ALight.h"
#include "URay.h"
#include <cfloat>
#include <glm/glm.hpp>

// ===========================================================================
//  Passthrough vertex shader
// ===========================================================================

static const char* VERT_SRC = R"GLSL(
#version 330 core
layout(location = 0) in vec2 aPos;
void main() { gl_Position = vec4(aPos, 0.0, 1.0); }
)GLSL";

// (TRACE_GLSL and main() are now generated by PostProcessPass::getGLSL)

// ===========================================================================
//  Static shader helpers
// ===========================================================================

static GLuint compileShader(GLenum type, const char* src)
{
    GLuint id = glCreateShader(type);
    glShaderSource(id, 1, &src, nullptr);
    glCompileShader(id);
    GLint ok;
    glGetShaderiv(id, GL_COMPILE_STATUS, &ok);
    if (!ok) {
        char buf[4096];
        glGetShaderInfoLog(id, sizeof(buf), nullptr, buf);
        std::cerr << "Shader compile error:\n" << buf << "\n";
    }
    return id;
}

static GLuint linkProgram(GLuint vert, GLuint frag)
{
    GLuint prog = glCreateProgram();
    glAttachShader(prog, vert);
    glAttachShader(prog, frag);
    glLinkProgram(prog);
    GLint ok;
    glGetProgramiv(prog, GL_LINK_STATUS, &ok);
    if (!ok) {
        char buf[4096];
        glGetProgramInfoLog(prog, sizeof(buf), nullptr, buf);
        std::cerr << "Program link error:\n" << buf << "\n";
    }
    return prog;
}

// ===========================================================================
//  GeometryPass implementation — uniforms + findClosest + occluded + getNormal
// ===========================================================================

GeometryPass::GeometryPass(const UScene& scene)
    : scene_(scene), brickTex_(0), cubeUBO_(0)
{
    for (const AActor* a : scene.Actors) {
        if (a->surface && a->surface->material.texture != 0) {
            brickTex_ = a->surface->material.texture;
            break;
        }
    }

    constexpr int MAX_CUBES = 256;
    glGenBuffers(1, &cubeUBO_);
    glBindBuffer(GL_UNIFORM_BUFFER, cubeUBO_);
    glBufferData(GL_UNIFORM_BUFFER, MAX_CUBES * 24 * sizeof(float), nullptr, GL_DYNAMIC_DRAW);
    glBindBuffer(GL_UNIFORM_BUFFER, 0);
}

GeometryPass::~GeometryPass()
{
    if (cubeUBO_) { glDeleteBuffers(1, &cubeUBO_); cubeUBO_ = 0; }
}

std::string GeometryPass::getGLSL() const
{
    std::map<int, SurfaceGLSLInfo> byType;
    for (const AActor* a : scene_.Actors) {
        SurfaceGLSLInfo info = a->surface->getGLSLInfo();
        if (byType.find(info.typeId) == byType.end())
            byType[info.typeId] = info;
    }

    std::string glsl;

    // Surface type uniforms + brick texture
    glsl += "\nuniform sampler2D uBrickTex;\n";
    for (auto& [tid, info] : byType)
        glsl += info.uniforms;

    // Per-type hit functions
    for (auto& [tid, info] : byType)
        glsl += info.hitFunc;

    // findClosest()
    glsl += "\nfloat findClosest(vec3 ro, vec3 rd, out int hitType, out int hitIdx) {\n"
            "    float best = 1e30;\n"
            "    hitType = -1; hitIdx = -1;\n";
    for (auto& [tid, info] : byType)
        glsl += "    for (int i = 0; i < " + info.countUniform + "; ++i) { "
                "float t = " + info.hitFuncName + "(ro, rd, i); "
                "if (t > 0.0 && t < best) { best = t; hitType = "
                + std::to_string(tid) + "; hitIdx = i; } }\n";
    glsl += "    return (hitType >= 0) ? best : -1.0;\n}\n";

    // occluded()
    glsl += "\nbool occluded(vec3 ro, vec3 rd, float maxT) {\n";
    for (auto& [tid, info] : byType)
        glsl += "    for (int i = 0; i < " + info.countUniform + "; ++i) { "
                "float t = " + info.hitFuncName + "(ro, rd, i); "
                "if (t > 0.0 && t < maxT) return true; }\n";
    glsl += "    return false;\n}\n";

    // getNormal()
    glsl += "\nvec3 getNormal(int type, int idx, vec3 p) {\n";
    for (auto& [tid, info] : byType)
        glsl += info.normalCase;
    glsl += "    return vec3(0.0, 1.0, 0.0);\n}\n";

    return glsl;
}

void GeometryPass::uploadUniforms(unsigned int prog,
                                   const UScene& scene,
                                   const ACamera& /*cam*/) const
{
    GLuint p = static_cast<GLuint>(prog);

    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, brickTex_);
    glUniform1i(glGetUniformLocation(p, "uBrickTex"), 0);

    constexpr int FLOATS_PER_CUBE = 24;
    std::vector<float> cubeData;
    cubeData.reserve(256 * FLOATS_PER_CUBE);

    std::map<int, int>         typeCounts;
    std::map<int, std::string> countUniformName;

    for (const AActor* a : scene.Actors) {
        SurfaceGLSLInfo info = a->surface->getGLSLInfo();
        int idx = typeCounts[info.typeId]++;
        countUniformName[info.typeId] = info.countUniform;

        if (info.typeId == 1) {
            float buf[FLOATS_PER_CUBE];
            static_cast<const CubeSurface*>(a->surface)->getUBOData(buf);
            cubeData.insert(cubeData.end(), buf, buf + FLOATS_PER_CUBE);
        } else {
            a->surface->uploadUniform(prog, idx);
        }
    }

    if (!cubeData.empty()) {
        glBindBuffer(GL_UNIFORM_BUFFER, cubeUBO_);
        glBufferSubData(GL_UNIFORM_BUFFER, 0,
                        cubeData.size() * sizeof(float), cubeData.data());
        glBindBuffer(GL_UNIFORM_BUFFER, 0);
    }
    glBindBufferBase(GL_UNIFORM_BUFFER, 0, cubeUBO_);

    for (auto& [tid, count] : typeCounts)
        glUniform1i(glGetUniformLocation(p, countUniformName[tid].c_str()), count);
}

// ===========================================================================
//  MaterialPass implementation — getDiffuse + getKa/Ks/Km/Shiny/Emit
// ===========================================================================

MaterialPass::MaterialPass(const UScene& scene)
    : scene_(scene)
{
}

std::string MaterialPass::getGLSL() const
{
    std::map<int, SurfaceGLSLInfo> byType;
    for (const AActor* a : scene_.Actors) {
        SurfaceGLSLInfo info = a->surface->getGLSLInfo();
        if (byType.find(info.typeId) == byType.end())
            byType[info.typeId] = info;
    }

    std::string glsl;

    glsl += "\nvec3 getDiffuse(int type, int idx, vec3 p) {\n";
    for (auto& [tid, info] : byType) glsl += info.diffuseCase;
    glsl += "    return vec3(1.0);\n}\n";

    glsl += "\nvec3 getKa(int t, int i) {\n";
    for (auto& [tid, info] : byType) glsl += info.kaCase;
    glsl += "    return vec3(0.0);\n}\n";

    glsl += "\nvec3 getKs(int t, int i) {\n";
    for (auto& [tid, info] : byType) glsl += info.ksCase;
    glsl += "    return vec3(0.0);\n}\n";

    glsl += "\nfloat getShiny(int t, int i) {\n";
    for (auto& [tid, info] : byType) glsl += info.shinyCase;
    glsl += "    return 0.0;\n}\n";

    glsl += "\nvec3 getKm(int t, int i) {\n";
    for (auto& [tid, info] : byType) glsl += info.kmCase;
    glsl += "    return vec3(0.0);\n}\n";

    glsl += "\nvec3 getEmit(int t, int i) {\n";
    for (auto& [tid, info] : byType)
        if (!info.emitCase.empty()) glsl += info.emitCase;
    glsl += "    return vec3(0.0);\n}\n";

    return glsl;
}

// ===========================================================================
//  DirectLightPass implementation — skyColor + shadeDirect
// ===========================================================================

DirectLightPass::DirectLightPass(const UScene& scene)
    : scene_(scene)
{
}

std::string DirectLightPass::getGLSL() const
{
    std::string constants, uniforms, functions, directBody;
    std::set<std::string> seenFuncs, seenConsts;

    for (const ALight* light : scene_.Lights) {
        LightGLSLInfo info = light->lightComp->getGLSLInfo();
        if (info.directContrib.empty()) continue;
        if (seenConsts.insert(info.constants).second)
            constants += info.constants;
        if (seenFuncs.insert(info.functions).second) {
            uniforms  += info.uniforms;
            functions += info.functions;
        }
        directBody += info.directContrib;
    }

    std::string glsl = constants + uniforms + functions;

    glsl +=
        "\nvec3 shadeDirect(vec3 p, vec3 n, int type, int idx) {\n"
        "    vec3 col = vec3(0.0);\n";
    glsl += directBody;
    glsl += "    return col;\n}\n";

    return glsl;
}

void DirectLightPass::uploadUniforms(unsigned int prog,
                                      const UScene& scene,
                                      const ACamera& /*cam*/) const
{
    using glm::value_ptr;
    GLuint p = static_cast<GLuint>(prog);

    int       nPL = 0;
    glm::vec3 plPos[4], plEffect[4];

    for (const ALight* light : scene.Lights) {
        if (auto* pl = dynamic_cast<PointLight*>(light->lightComp)) {
            if (nPL >= 4) continue;
            plPos[nPL]    = pl->LightPos;
            plEffect[nPL] = pl->LightColor * pl->LightIntensity;
            ++nPL;
        }
    }

    glUniform1i(glGetUniformLocation(p, "uNPointLight"), nPL);
    if (nPL > 0) {
        glUniform3fv(glGetUniformLocation(p, "uPLPos"),    nPL, value_ptr(plPos[0]));
        glUniform3fv(glGetUniformLocation(p, "uPLEffect"), nPL, value_ptr(plEffect[0]));
    }
}

// ===========================================================================
//  IndirectLightPass implementation — shadeIndirect + shade combiner
// ===========================================================================

IndirectLightPass::IndirectLightPass(const UScene& scene)
    : scene_(scene)
{
}

std::string IndirectLightPass::getGLSL() const
{
    std::string constants, uniforms, functions, indirectBody;
    std::set<std::string> seenFuncs, seenConsts;

    for (const ALight* light : scene_.Lights) {
        LightGLSLInfo info = light->lightComp->getGLSLInfo();
        if (info.indirectContrib.empty()) continue;
        if (seenConsts.insert(info.constants).second)
            constants += info.constants;
        if (seenFuncs.insert(info.functions).second) {
            uniforms  += info.uniforms;
            functions += info.functions;
        }
        indirectBody += info.indirectContrib;
    }

    // Sky gradient uniforms + skyColor() — always emitted here so trace() and
    // shadeEnvLight() can both call skyColor() regardless of light configuration.
    std::string glsl =
        "\nuniform vec3  uSkyHorizon;\n"
        "uniform vec3  uSkyZenith;\n"
        "uniform float uSkyExp;\n"
        "\nvec3 skyColor(vec3 d) {\n"
        "    float t = clamp(normalize(d).y * 0.5 + 0.5, 0.0, 1.0);\n"
        "    return mix(uSkyHorizon, uSkyZenith, pow(t, uSkyExp));\n"
        "}\n";

    glsl += constants + uniforms + functions;

    glsl +=
        "\nvec3 shadeIndirect(vec3 p, vec3 n, int type, int idx) {\n"
        "    vec3 col = vec3(0.0);\n";
    glsl += indirectBody;
    glsl += "    return col;\n}\n";

    // shade = direct + indirect; always defined so TRACE uses a single call
    glsl +=
        "\nvec3 shade(vec3 p, vec3 n, int type, int idx) {\n"
        "    return shadeDirect(p, n, type, idx) + shadeIndirect(p, n, type, idx);\n"
        "}\n";

    return glsl;
}

void IndirectLightPass::uploadUniforms(unsigned int prog,
                                        const UScene& scene,
                                        const ACamera& /*cam*/) const
{
    GLuint p = static_cast<GLuint>(prog);

    // Defaults — bright midday sky
    glm::vec3 horizon(0.95f, 0.92f, 0.82f);
    glm::vec3 zenith (0.30f, 0.60f, 1.00f);
    float     skyExp = 0.6f;
    glm::vec3 envEffect(0.0f);

    for (const ALight* light : scene.Lights) {
        if (auto* el = dynamic_cast<EnvironmentLight*>(light->lightComp)) {
            horizon   = el->horizonColor;
            zenith    = el->zenithColor;
            skyExp    = el->skyExp;
            envEffect = el->LightColor * el->LightIntensity;
        }
    }

    glUniform3fv(glGetUniformLocation(p, "uSkyHorizon"), 1, glm::value_ptr(horizon));
    glUniform3fv(glGetUniformLocation(p, "uSkyZenith"),  1, glm::value_ptr(zenith));
    glUniform1f (glGetUniformLocation(p, "uSkyExp"),     skyExp);
    glUniform3fv(glGetUniformLocation(p, "uEnvEffect"),  1, glm::value_ptr(envEffect));
}

// ===========================================================================
//  PostProcessPass implementation
//  AA and gamma are compile-time constants from RenderConfig.h.
//  No per-frame uniforms — uploadUniforms is declared no-op in the header.
// ===========================================================================

std::string PostProcessPass::getGLSL() const
{
    return
        // ── Sampling helpers ──────────────────────────────────────────────
        "\n"
        "float _hash(vec2 p, float s) {\n"
        "    return fract(sin(dot(p + s, vec2(127.1, 311.7))) * 43758.5453);\n"
        "}\n"
        "float _halton(int idx, int base) {\n"
        "    float f = 1.0, r = 0.0;\n"
        "    for (int k = 0; k < 8; ++k) {\n"
        "        if (idx == 0) break;\n"
        "        f /= float(base);\n"
        "        r += f * float(idx - (idx / base) * base);\n"
        "        idx /= base;\n"
        "    }\n"
        "    return r;\n"
        "}\n"

        // ── trace() — reflection loop ─────────────────────────────────────
        "\nvec3 trace(vec3 ro, vec3 rd)\n"
        "{\n"
        "    vec3 accum  = vec3(0.0);\n"
        "    vec3 weight = vec3(1.0);\n"
        "    for (int depth = 0; depth <= MAX_DEPTH; ++depth) {\n"
        "        int   type, idx;\n"
        "        float t = findClosest(ro, rd, type, idx);\n"
        "        if (type < 0) { accum += weight * skyColor(rd); break; }\n"
        "        vec3 p = ro + t * rd;\n"
        "        vec3 n = getNormal(type, idx, p);\n"
        "        accum += weight * (getEmit(type, idx) + getKa(type, idx));\n"
        "        accum += weight * shade(p, n, type, idx);\n"
        "        vec3 km = getKm(type, idx);\n"
        "        if (depth >= MAX_DEPTH || dot(km, km) < 1e-6) break;\n"
        "        weight *= km;\n"
        "        ro = p + 1e-4 * n;\n"
        "        rd = reflect(rd, n);\n"
        "    }\n"
        "    return accum;\n"
        "}\n"

        // ── main() ────────────────────────────────────────────────────────
        "\nvoid main()\n"
        "{\n"
        "    vec3 col = vec3(0.0);\n"
        "    vec2 pix = floor(gl_FragCoord.xy);\n"

        // No AA — single centre sample
        "#if AA_ENABLE == 0\n"
        "    {\n"
        "        float su = uL + (uR - uL) * (pix.x + 0.5) / float(uWidth);\n"
        "        float sv = uB + (uT - uB) * (pix.y + 0.5) / float(uHeight);\n"
        "        col = trace(uEye, normalize(-uD * uW + su * uU + sv * uV));\n"
        "    }\n"

        // Random jitter
        "#elif AA_MODE == 1\n"
        "    for (int i = 0; i < AA_GRID * AA_GRID; ++i) {\n"
        "        float ox = _hash(gl_FragCoord.xy, float(i) * 1.7);\n"
        "        float oy = _hash(gl_FragCoord.xy, float(i) * 2.3 + 50.0);\n"
        "        float su = uL + (uR - uL) * (pix.x + ox) / float(uWidth);\n"
        "        float sv = uB + (uT - uB) * (pix.y + oy) / float(uHeight);\n"
        "        col += trace(uEye, normalize(-uD * uW + su * uU + sv * uV));\n"
        "    }\n"
        "    col /= float(AA_GRID * AA_GRID);\n"

        // Stratified jittered grid (recommended)
        "#elif AA_MODE == 2\n"
        "    for (int sy = 0; sy < AA_GRID; ++sy)\n"
        "        for (int sx = 0; sx < AA_GRID; ++sx) {\n"
        "            float jx = _hash(gl_FragCoord.xy, float(sx*7 + sy*3)       ) - 0.5;\n"
        "            float jy = _hash(gl_FragCoord.xy, float(sx*3 + sy*11)+100.0) - 0.5;\n"
        "            float fx = pix.x + (float(sx) + 0.5 + jx) / float(AA_GRID);\n"
        "            float fy = pix.y + (float(sy) + 0.5 + jy) / float(AA_GRID);\n"
        "            float su = uL + (uR - uL) * fx / float(uWidth);\n"
        "            float sv = uB + (uT - uB) * fy / float(uHeight);\n"
        "            col += trace(uEye, normalize(-uD * uW + su * uU + sv * uV));\n"
        "        }\n"
        "    col /= float(AA_GRID * AA_GRID);\n"

        // Halton low-discrepancy sequence (best quality, deterministic)
        "#elif AA_MODE == 3\n"
        "    for (int i = 0; i < AA_GRID * AA_GRID; ++i) {\n"
        "        float ox = _halton(i + 1, 2);\n"
        "        float oy = _halton(i + 1, 3);\n"
        "        float su = uL + (uR - uL) * (pix.x + ox) / float(uWidth);\n"
        "        float sv = uB + (uT - uB) * (pix.y + oy) / float(uHeight);\n"
        "        col += trace(uEye, normalize(-uD * uW + su * uU + sv * uV));\n"
        "    }\n"
        "    col /= float(AA_GRID * AA_GRID);\n"
        "#endif\n"

        // Reinhard tone mapping + optional gamma
        "    col = col / (col + vec3(1.0));\n"
        "#if GAMMA_ENABLE\n"
        "    col = pow(col, vec3(1.0 / GAMMA_VALUE));\n"
        "#endif\n"
        "    fragColor = vec4(col, 1.0);\n"
        "}\n";
}

// ===========================================================================
//  URayTracing — GPU renderer methods
// ===========================================================================

URayTracing::URayTracing()  = default;
URayTracing::~URayTracing() = default;

void URayTracing::Init(const UScene& scene)
{
    geometryPass_      = std::make_unique<GeometryPass>(scene);
    materialPass_      = std::make_unique<MaterialPass>(scene);
    directLightPass_   = std::make_unique<DirectLightPass>(scene);
    indirectLightPass_ = std::make_unique<IndirectLightPass>(scene);
    postProcessPass_   = std::make_unique<PostProcessPass>();

    // Assemble fragment shader in dependency order:
    //   preamble          (version + defines + output + camera uniforms)
    //   GeometryPass      (surface uniforms + findClosest + occluded + getNormal)
    //   MaterialPass      (getDiffuse + getKa/Ks/Km/Shiny/Emit)
    //   DirectLightPass   (skyColor + shadePointLight + shadeDirect)
    //   IndirectLightPass (shadeEnvLight + shadeIndirect + shade combiner)
    //   PostProcessPass   (trace loop + AA main + gamma)
    std::string fragSrc =
        "#version 330 core\n"
        "#define ENV_LIGHT_SAMPLES "   + std::to_string(ENV_LIGHT_SAMPLES)   + "\n" +
        "#define GI_BOUNCE_DEPTH "     + std::to_string(GI_BOUNCE_DEPTH)     + "\n" +
        "#define SOFT_SHADOW_SAMPLES " + std::to_string(SOFT_SHADOW_SAMPLES) + "\n" +
        "#define SOFT_SHADOW_RADIUS "  + std::to_string(SOFT_SHADOW_RADIUS)  + "\n" +
        "#define AA_ENABLE "           + std::to_string(AA_ENABLE)           + "\n" +
        "#define AA_GRID "             + std::to_string(AA_GRID)             + "\n" +
        "#define AA_MODE "             + std::to_string(AA_MODE)             + "\n" +
        "#define GAMMA_ENABLE "        + std::to_string(GAMMA_ENABLE)        + "\n" +
        "#define GAMMA_VALUE "         + std::to_string(GAMMA_VALUE)         + "\n" +
        "#define MAX_DEPTH 5\n"
        "out vec4 fragColor;\n"
        "uniform vec3  uEye, uU, uV, uW;\n"
        "uniform float uL, uR, uB, uT, uD;\n"
        "uniform int   uWidth, uHeight;\n"
        + geometryPass_->getGLSL()
        + materialPass_->getGLSL()
        + directLightPass_->getGLSL()
        + indirectLightPass_->getGLSL()
        + postProcessPass_->getGLSL();

    // Dump fragment shader with line numbers for debugging
    {
        std::istringstream ss(fragSrc);
        std::string line;
        int ln = 1;
        std::cerr << "\n===== FRAGMENT SHADER SOURCE =====\n";
        while (std::getline(ss, line))
            std::cerr << ln++ << ": " << line << "\n";
        std::cerr << "===== END =====\n\n";
    }

    GLuint vert = compileShader(GL_VERTEX_SHADER,   VERT_SRC);
    GLuint frag = compileShader(GL_FRAGMENT_SHADER, fragSrc.c_str());
    prog_ = linkProgram(vert, frag);
    glDeleteShader(vert);
    glDeleteShader(frag);

    // Bind the CubeBlock UBO to binding point 0
    GLuint blockIdx = glGetUniformBlockIndex(prog_, "CubeBlock");
    if (blockIdx != GL_INVALID_INDEX)
        glUniformBlockBinding(prog_, blockIdx, 0);

    // Fullscreen quad (NDC triangle pair)
    float quadVerts[] = {
        -1.0f, -1.0f,   1.0f, -1.0f,   1.0f,  1.0f,
        -1.0f, -1.0f,   1.0f,  1.0f,  -1.0f,  1.0f
    };
    glGenVertexArrays(1, &vao_);
    glGenBuffers(1, &vbo_);
    glBindVertexArray(vao_);
    glBindBuffer(GL_ARRAY_BUFFER, vbo_);
    glBufferData(GL_ARRAY_BUFFER, sizeof(quadVerts), quadVerts, GL_STATIC_DRAW);
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 2 * sizeof(float), (void*)0);
    glEnableVertexAttribArray(0);
    glBindVertexArray(0);

    glUseProgram(prog_);
}

void URayTracing::RenderFrame(const UScene& scene, const ACamera& cam,
                               const RenderSettings& /*s*/)
{
    // AA and gamma are compile-time constants (RenderConfig.h) baked into
    // the shader at Init() — nothing to configure per-frame here.
    uploadCameraUniforms(cam, scene);
    geometryPass_->uploadUniforms(prog_, scene, cam);
    // materialPass_ uses base no-op (material data covered by geometry uniforms)
    directLightPass_->uploadUniforms(prog_, scene, cam);
    indirectLightPass_->uploadUniforms(prog_, scene, cam);
    postProcessPass_->uploadUniforms(prog_, scene, cam);

    glClear(GL_COLOR_BUFFER_BIT);
    glBindVertexArray(vao_);
    glDrawArrays(GL_TRIANGLES, 0, 6);
}

void URayTracing::Cleanup()
{
    geometryPass_.reset();
    materialPass_.reset();
    directLightPass_.reset();
    indirectLightPass_.reset();
    postProcessPass_.reset();
    glDeleteVertexArrays(1, &vao_);
    glDeleteBuffers(1, &vbo_);
    glDeleteProgram(prog_);
    vao_ = vbo_ = prog_ = 0;
}

void URayTracing::uploadCameraUniforms(const ACamera& cam, const UScene& scene) const
{
    using glm::value_ptr;
    GLuint p = static_cast<GLuint>(prog_);
    glUniform3fv(glGetUniformLocation(p, "uEye"), 1, value_ptr(cam.eye));
    glUniform3fv(glGetUniformLocation(p, "uU"),   1, value_ptr(cam.u));
    glUniform3fv(glGetUniformLocation(p, "uV"),   1, value_ptr(cam.v));
    glUniform3fv(glGetUniformLocation(p, "uW"),   1, value_ptr(cam.w));
    glUniform1f (glGetUniformLocation(p, "uL"),  cam.l);
    glUniform1f (glGetUniformLocation(p, "uR"),  cam.r);
    glUniform1f (glGetUniformLocation(p, "uB"),  cam.b);
    glUniform1f (glGetUniformLocation(p, "uT"),  cam.t);
    glUniform1f (glGetUniformLocation(p, "uD"),  cam.d);
    glUniform1i (glGetUniformLocation(p, "uWidth"),  scene.width);
    glUniform1i (glGetUniformLocation(p, "uHeight"), scene.height);
}

// ===========================================================================
//  CPU ray tracer
//
//  Blinn-Phong model (per lecture):
//    L = ka*Ia + sum_lights[ kd*Il*max(0,n·l) + ks*Il*max(0,n·h)^p ] * (1-shadow)
//  where h = normalize(l + v),  Ia = white (1,1,1) unit ambient.
//
//  mode 0  TraceQ2  Phong + shadow, no reflection
//  mode 1  TraceQ3  Phong + shadow + km mirror reflection (recursive, MAX_DEPTH 5)
//
//  Lights are read from scene.Lights (PointLight components only for Q2/Q3 direct).
//  EnvironmentLight (GI) is handled inside TraceQ3 via ComputePhong → illuminate().
// ===========================================================================

void URayTracing::Render(UScene& scene, ACamera& camera, int mode,
                          const RenderSettings& s) const
{
    scene.outputImage.assign(scene.width * scene.height * 3, 0.0f);

    const bool doAA = s.enableAA && s.aaGrid > 1;

    for (int iy = 0; iy < scene.height; ++iy)
        for (int ix = 0; ix < scene.width; ++ix)
        {
            glm::vec3 color;
            if (doAA) {
                color = TracePixelAA(ix, iy, mode, scene, camera, s.aaGrid, s.aaMode);
            } else {
                URay ray = camera.generateRay(ix, iy, scene.width, scene.height);
                switch (mode) {
                case 0:  color = TraceQ2(ray, scene, camera); break;
                case 1:  color = TraceQ3(ray, scene, camera); break;
                default: color = glm::vec3(0.0f);
                }
            }
            int idx = (iy * scene.width + ix) * 3;
            scene.outputImage[idx + 0] = color.r;
            scene.outputImage[idx + 1] = color.g;
            scene.outputImage[idx + 2] = color.b;
        }

    // Reinhard tone mapping + gamma — applied after tracing so AA averages stay linear
    if (s.enableGamma)
        ApplyToneGamma(scene, s.gamma);
}

// ---------------------------------------------------------------------------
//  TracePixelAA — multi-sample AA with selectable pattern
//
//  aaMode 1 = Random jitter         — fast, some noise
//  aaMode 2 = Stratified jitter     — recommended; uniform grid + random offset
//  aaMode 3 = Halton sequence       — best quality; deterministic, low-discrepancy
//
//  All modes cast aaGrid*aaGrid rays; offsets are in [0,1] (pixel space).
// ---------------------------------------------------------------------------
glm::vec3 URayTracing::TracePixelAA(int ix, int iy, int renderMode,
                                     const UScene& scene, const ACamera& cam,
                                     int aaGrid, int aaMode) const
{
    thread_local std::mt19937 rng(std::random_device{}());
    std::uniform_real_distribution<float> dist(0.0f, 1.0f);

    // Halton helper (base 2 or 3)
    auto halton = [](int idx, int base) -> float {
        float f = 1.0f, r = 0.0f;
        for (int i = idx; i > 0; i /= base) { f /= base; r += f * (i % base); }
        return r;
    };

    const int total = aaGrid * aaGrid;
    glm::vec3 accum(0.0f);

    for (int s = 0; s < total; ++s) {
        float jx, jy;   // sub-pixel offset in [0, 1]

        if (aaMode == 2) {
            // Stratified: sample within cell (sx, sy)
            int sx = s % aaGrid, sy = s / aaGrid;
            jx = (float(sx) + dist(rng)) / float(aaGrid);
            jy = (float(sy) + dist(rng)) / float(aaGrid);
        } else if (aaMode == 3) {
            // Halton: low-discrepancy deterministic sequence
            jx = halton(s + 1, 2);
            jy = halton(s + 1, 3);
        } else {
            // Random: uniform jitter
            jx = dist(rng);
            jy = dist(rng);
        }

        URay ray = cam.generateRayJittered(ix, iy, scene.width, scene.height, jx, jy);
        glm::vec3 c;
        switch (renderMode) {
        case 0:  c = TraceQ2(ray, scene, cam); break;
        case 1:  c = TraceQ3(ray, scene, cam); break;
        default: c = glm::vec3(0.0f);
        }
        accum += c;
    }
    return accum / float(total);
}

// ---------------------------------------------------------------------------
//  ApplyToneGamma — Reinhard tone mapping + gamma correction in-place
//  output = pow(x / (x + 1), 1/gamma)  (per channel)
// ---------------------------------------------------------------------------
void URayTracing::ApplyToneGamma(UScene& scene, float gamma) const
{
    const float invGamma = 1.0f / gamma;
    for (int i = 0; i < (int)scene.outputImage.size(); i += 3) {
        float r = scene.outputImage[i + 0];
        float g = scene.outputImage[i + 1];
        float b = scene.outputImage[i + 2];
        r = r / (r + 1.0f);
        g = g / (g + 1.0f);
        b = b / (b + 1.0f);
        scene.outputImage[i + 0] = std::pow(r, invGamma);
        scene.outputImage[i + 1] = std::pow(g, invGamma);
        scene.outputImage[i + 2] = std::pow(b, invGamma);
    }
}

bool URayTracing::FindClosestHit(const URay& ray, const UScene& scene,
                                  float& outT, const AActor*& outActor) const
{
    outT = FLT_MAX; outActor = nullptr;
    for (const AActor* actor : scene.Actors) {
        float t;
        if (actor->surface->intersect(ray, t) && t < outT)
            { outT = t; outActor = actor; }
    }
    return outActor != nullptr;
}

// ---------------------------------------------------------------------------
//  TraceQ2 — Blinn-Phong + shadow rays, no reflection
//  Reads PointLights from scene.Lights.
//  Ambient: Ia = (1,1,1) white unit intensity (HW3 spec).
// ---------------------------------------------------------------------------
glm::vec3 URayTracing::TraceQ2(const URay& ray, const UScene& scene,
                                const ACamera& camera) const
{
    float t; const AActor* actor;
    if (!FindClosestHit(ray, scene, t, actor)) return glm::vec3(0.0f);

    glm::vec3 p   = ray.origin + t * ray.direction;
    glm::vec3 n   = actor->surface->getNormal(p);
    glm::vec3 v   = glm::normalize(camera.eye - p);
    const Material& mat = actor->surface->material;

    // Ambient: Ia = (1,1,1)
    glm::vec3 color = mat.ka;

    for (const ALight* light : scene.Lights)
    {
        PointLight* pl = dynamic_cast<PointLight*>(light->lightComp);
        if (!pl) continue;  // skip EnvironmentLight for Q2

        glm::vec3 toLight = pl->LightPos - p;
        float     dist    = glm::length(toLight);
        glm::vec3 l       = toLight / dist;

        float NdotL = glm::dot(n, l);
        if (NdotL <= 0.0f) continue;

        // Shadow ray (offset by epsilon along normal to avoid self-intersection)
        URay shadowRay(p + 1e-4f * n, l);
        bool inShadow = false;
        for (const AActor* other : scene.Actors) {
            float st;
            if (other->surface->intersect(shadowRay, st) && st < dist)
                { inShadow = true; break; }
        }
        if (inShadow) continue;

        glm::vec3 Il = pl->LightColor * pl->LightIntensity;

        // Diffuse
        color += mat.kd * Il * NdotL;

        // Specular — Blinn-Phong: h = normalize(l + v)
        if (mat.shininess > 0.0f) {
            glm::vec3 h     = glm::normalize(l + v);
            float     NdotH = glm::max(0.0f, glm::dot(n, h));
            color += mat.ks * Il * glm::pow(NdotH, mat.shininess);
        }
    }

    return glm::clamp(color, 0.0f, 1.0f);
}

// ---------------------------------------------------------------------------
//  TraceQ3 — Q2 + km mirror reflection (recursive up to MAX_DEPTH)
//  Also supports EnvironmentLight GI via ComputePhong → illuminate().
// ---------------------------------------------------------------------------
glm::vec3 URayTracing::TraceQ3(const URay& ray, const UScene& scene,
                                const ACamera& camera, int depth) const
{
    const int MAX_DEPTH = 5;

    // Read sky gradient from the scene's EnvironmentLight; fall back to defaults.
    glm::vec3 skyHorizon(0.95f, 0.92f, 0.82f);
    glm::vec3 skyZenith (0.30f, 0.60f, 1.00f);
    float     skyExpVal = 0.6f;
    for (const ALight* light : scene.Lights) {
        if (auto* el = dynamic_cast<EnvironmentLight*>(light->lightComp)) {
            skyHorizon = el->horizonColor;
            skyZenith  = el->zenithColor;
            skyExpVal  = el->skyExp;
            break;
        }
    }
    auto skyColor = [&](const glm::vec3& dir) -> glm::vec3 {
        float t = glm::clamp(glm::normalize(dir).y * 0.5f + 0.5f, 0.0f, 1.0f);
        return glm::mix(skyHorizon, skyZenith, std::pow(t, skyExpVal));
    };

    float hitT; const AActor* actor;
    if (!FindClosestHit(ray, scene, hitT, actor)) return skyColor(ray.direction);

    glm::vec3 p = ray.origin + hitT * ray.direction;
    glm::vec3 n = actor->surface->getNormal(p);
    const Material& mat = actor->surface->material;

    // Emissive + Ambient (Ia = (1,1,1))
    glm::vec3 color = mat.emissive + mat.ka;

    // Phong + shadow from all scene lights (PointLight direct + EnvironmentLight GI)
    color += ComputePhong(p, n, actor, ray, scene, camera, depth);

    // Mirror reflection
    glm::vec3 km = mat.km;
    if (depth < MAX_DEPTH && glm::dot(km, km) > 0.0f) {
        glm::vec3 reflDir = glm::reflect(ray.direction, n);
        URay      reflRay(p + 1e-4f * n, reflDir);
        color += km * TraceQ3(reflRay, scene, camera, depth + 1);
    }

    return glm::clamp(color, 0.0f, 1.0f);
}

// ---------------------------------------------------------------------------
//  ComputePhong — sums illuminate() from all lights in scene.Lights
//  (PointLight: Blinn-Phong + soft shadow / EnvironmentLight: GI)
// ---------------------------------------------------------------------------
glm::vec3 URayTracing::ComputePhong(const glm::vec3& p, const glm::vec3& n,
                                     const AActor* actor, const URay& ray,
                                     const UScene& scene, const ACamera& camera,
                                     int depth) const
{
    glm::vec3 color(0.0f);
    for (const ALight* light : scene.Lights)
        color += light->illuminate(p, n, actor, ray, scene, camera, depth, this);
    return color;
}
