// GPU renderer headers (must come before any GLFW / gl.h inclusion)
#include <GL/glew.h>
#include <glm/gtc/type_ptr.hpp>
#include <iostream>
#include <string>
#include <map>
#include <set>
#include <random>
#include <cmath>

// Surface / light types for IntersectionPass and LightingPass implementations
#include "SphereSurface.h"
#include "CubeSurface.h"
#include "PlaneSurface.h"
#include "../Light/PointLight.h"
#include "../Light/EnvironmentLight.h"

// Pass headers (declarations only — implementations are below)
#include "IntersectionPass.h"
#include "LightingPass.h"

#include "URayTracing.h"
#include "UScene.h"
#include "ACamera.h"
#include "AActor.h"
#include "../Light/ALight.h"
#include "URay.h"
#include <cfloat>
#include <glm/glm.hpp>

// ===========================================================================
//  Passthrough vertex shader
// ===========================================================================

static const char* VERT_SRC = R"GLSL(
#version 330 core
layout(location = 0) in vec2 aPos;
void main() { gl_Position = vec4(aPos, 0.0, 1.0); }
)GLSL";

// ===========================================================================
//  Fixed trace loop + ray-generation entry point.
//  All functions it calls (findClosest, skyColor, getEmit, shade, getKm,
//  getNormal) are generated by IntersectionPass / LightingPass.
//  Camera uniforms (uEye etc.) are declared in the preamble by URayTracing::Init.
// ===========================================================================

static const char* TRACE_GLSL = R"GLSL(
vec3 trace(vec3 ro, vec3 rd)
{
    vec3 accum  = vec3(0.0);
    vec3 weight = vec3(1.0);

    for (int depth = 0; depth <= MAX_DEPTH; ++depth) {
        int   type, idx;
        float t = findClosest(ro, rd, type, idx);

        if (type < 0) {
            accum += weight * skyColor(rd);
            break;
        }

        vec3 p = ro + t * rd;
        vec3 n = getNormal(type, idx, p);

        accum += weight * getEmit(type, idx);
        accum += weight * shade(p, n, type, idx);

        vec3 km = getKm(type, idx);
        if (depth >= MAX_DEPTH || dot(km, km) < 1e-6) break;

        weight *= km;
        ro = p + 1e-4 * n;
        rd = reflect(rd, n);
    }
    return clamp(accum, 0.0, 1.0);
}

void main()
{
    float aspect = float(uWidth) / float(uHeight);
    float su = (uL + (uR - uL) * gl_FragCoord.x / float(uWidth)) * aspect;
    float sv =  uB + (uT - uB) * gl_FragCoord.y / float(uHeight);
    vec3  rd = normalize(-uD * uW + su * uU + sv * uV);
    fragColor = vec4(trace(uEye, rd), 1.0);
}
)GLSL";

// ===========================================================================
//  Static shader helpers
// ===========================================================================

static GLuint compileShader(GLenum type, const char* src)
{
    GLuint id = glCreateShader(type);
    glShaderSource(id, 1, &src, nullptr);
    glCompileShader(id);
    GLint ok;
    glGetShaderiv(id, GL_COMPILE_STATUS, &ok);
    if (!ok) {
        char buf[4096];
        glGetShaderInfoLog(id, sizeof(buf), nullptr, buf);
        std::cerr << "Shader compile error:\n" << buf << "\n";
    }
    return id;
}

static GLuint linkProgram(GLuint vert, GLuint frag)
{
    GLuint prog = glCreateProgram();
    glAttachShader(prog, vert);
    glAttachShader(prog, frag);
    glLinkProgram(prog);
    GLint ok;
    glGetProgramiv(prog, GL_LINK_STATUS, &ok);
    if (!ok) {
        char buf[4096];
        glGetProgramInfoLog(prog, sizeof(buf), nullptr, buf);
        std::cerr << "Program link error:\n" << buf << "\n";
    }
    return prog;
}

// ===========================================================================
//  IntersectionPass implementation
// ===========================================================================

IntersectionPass::IntersectionPass(const UScene& scene)
    : scene_(scene), brickTex_(0), cubeUBO_(0)
{
    for (const AActor* a : scene.Actors) {
        if (a->surface && a->surface->material.texture != 0) {
            brickTex_ = a->surface->material.texture;
            break;
        }
    }

    // Pre-allocate the cube UBO (256 cubes × 6 vec4s × 16 bytes = 24 KB)
    constexpr int MAX_CUBES = 256;
    glGenBuffers(1, &cubeUBO_);
    glBindBuffer(GL_UNIFORM_BUFFER, cubeUBO_);
    glBufferData(GL_UNIFORM_BUFFER, MAX_CUBES * 24 * sizeof(float), nullptr, GL_DYNAMIC_DRAW);
    glBindBuffer(GL_UNIFORM_BUFFER, 0);
}

IntersectionPass::~IntersectionPass()
{
    if (cubeUBO_) { glDeleteBuffers(1, &cubeUBO_); cubeUBO_ = 0; }
}

std::string IntersectionPass::getGLSL() const
{
    // Collect unique surface types ordered by typeId
    std::map<int, SurfaceGLSLInfo> byType;
    for (const AActor* a : scene_.Actors) {
        SurfaceGLSLInfo info = a->surface->getGLSLInfo();
        if (byType.find(info.typeId) == byType.end())
            byType[info.typeId] = info;
    }

    std::string glsl;

    // 1. Brick texture uniform + per-type geometry uniforms
    glsl += "\nuniform sampler2D uBrickTex;\n";
    for (auto& [tid, info] : byType)
        glsl += info.uniforms;

    // 2. Hit functions (one per surface type)
    for (auto& [tid, info] : byType)
        glsl += info.hitFunc;

    // 3. findClosest() — iterates every type's array
    glsl += "\nfloat findClosest(vec3 ro, vec3 rd, out int hitType, out int hitIdx) {\n"
            "    float best = 1e30;\n"
            "    hitType = -1; hitIdx = -1;\n";
    for (auto& [tid, info] : byType)
        glsl += "    for (int i = 0; i < " + info.countUniform + "; ++i) { "
                "float t = " + info.hitFuncName + "(ro, rd, i); "
                "if (t > 0.0 && t < best) { best = t; hitType = "
                + std::to_string(tid) + "; hitIdx = i; } }\n";
    glsl += "    return (hitType >= 0) ? best : -1.0;\n}\n";

    // 4. occluded()
    glsl += "\nbool occluded(vec3 ro, vec3 rd, float maxT) {\n";
    for (auto& [tid, info] : byType)
        glsl += "    for (int i = 0; i < " + info.countUniform + "; ++i) { "
                "float t = " + info.hitFuncName + "(ro, rd, i); "
                "if (t > 0.0 && t < maxT) return true; }\n";
    glsl += "    return false;\n}\n";

    // 5. getNormal() dispatcher
    glsl += "\nvec3 getNormal(int type, int idx, vec3 p) {\n";
    for (auto& [tid, info] : byType)
        glsl += info.normalCase;
    glsl += "    return vec3(0.0, 1.0, 0.0);\n}\n";

    // 6. getDiffuse() dispatcher
    glsl += "\nvec3 getDiffuse(int type, int idx, vec3 p) {\n";
    for (auto& [tid, info] : byType)
        glsl += info.diffuseCase;
    glsl += "    return vec3(1.0);\n}\n";

    // 7. Property getters
    glsl += "\nvec3 getKa(int t, int i) {\n";
    for (auto& [tid, info] : byType) glsl += info.kaCase;
    glsl += "    return vec3(0.0);\n}\n";

    glsl += "\nvec3 getKs(int t, int i) {\n";
    for (auto& [tid, info] : byType) glsl += info.ksCase;
    glsl += "    return vec3(0.0);\n}\n";

    glsl += "\nfloat getShiny(int t, int i) {\n";
    for (auto& [tid, info] : byType) glsl += info.shinyCase;
    glsl += "    return 0.0;\n}\n";

    glsl += "\nvec3 getKm(int t, int i) {\n";
    for (auto& [tid, info] : byType) glsl += info.kmCase;
    glsl += "    return vec3(0.0);\n}\n";

    glsl += "\nvec3 getEmit(int t, int i) {\n";
    for (auto& [tid, info] : byType)
        if (!info.emitCase.empty()) glsl += info.emitCase;
    glsl += "    return vec3(0.0);\n}\n";

    return glsl;
}

void IntersectionPass::uploadUniforms(unsigned int prog,
                                       const UScene& scene,
                                       const ACamera& /*cam*/) const
{
    GLuint p = static_cast<GLuint>(prog);

    // Brick texture → unit 0
    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, brickTex_);
    glUniform1i(glGetUniformLocation(p, "uBrickTex"), 0);

    // ------------------------------------------------------------------
    // Collect cube data into a CPU buffer, then upload as one UBO write.
    // Spheres and planes still use per-uniform uploads (small count).
    // ------------------------------------------------------------------
    constexpr int FLOATS_PER_CUBE = 24; // 6 vec4s
    std::vector<float> cubeData;
    cubeData.reserve(256 * FLOATS_PER_CUBE);

    std::map<int, int>         typeCounts;
    std::map<int, std::string> countUniformName;

    for (const AActor* a : scene.Actors) {
        SurfaceGLSLInfo info = a->surface->getGLSLInfo();
        int idx = typeCounts[info.typeId]++;
        countUniformName[info.typeId] = info.countUniform;

        if (info.typeId == 1) {
            // Cube — pack into UBO buffer
            float buf[FLOATS_PER_CUBE];
            static_cast<const CubeSurface*>(a->surface)->getUBOData(buf);
            cubeData.insert(cubeData.end(), buf, buf + FLOATS_PER_CUBE);
        } else {
            // Sphere / Plane — per-uniform upload as before
            a->surface->uploadUniform(prog, idx);
        }
    }

    // Upload cube UBO in one call
    if (!cubeData.empty()) {
        glBindBuffer(GL_UNIFORM_BUFFER, cubeUBO_);
        glBufferSubData(GL_UNIFORM_BUFFER, 0,
                        cubeData.size() * sizeof(float), cubeData.data());
        glBindBuffer(GL_UNIFORM_BUFFER, 0);
    }
    glBindBufferBase(GL_UNIFORM_BUFFER, 0, cubeUBO_);

    // Upload type counts
    for (auto& [tid, count] : typeCounts)
        glUniform1i(glGetUniformLocation(p, countUniformName[tid].c_str()), count);
}

// ===========================================================================
//  LightingPass implementation
// ===========================================================================

LightingPass::LightingPass(const UScene& scene)
    : scene_(scene)
{
}

std::string LightingPass::getGLSL() const
{
    // Collect per-type info (deduplicated by function body string)
    std::string constants, uniforms, functions, shadeBody;
    std::set<std::string> seenFunctions;
    std::set<std::string> seenConstants;

    for (const ALight* light : scene_.Lights) {
        LightGLSLInfo info = light->lightComp->getGLSLInfo();
        if (seenConstants.insert(info.constants).second)
            constants += info.constants;
        if (seenFunctions.insert(info.functions).second) {
            uniforms  += info.uniforms;
            functions += info.functions;
        }
        shadeBody += info.shadeContrib;
    }

    std::string glsl;
    glsl += constants;
    glsl += uniforms;

    // skyColor is fixed (no light-type dependency)
    glsl +=
        "\nvec3 skyColor(vec3 d) {\n"
        "    float t = 0.5 * (normalize(d).y + 1.0);\n"
        "    return mix(vec3(1.0), vec3(0.5, 0.7, 1.0), t);\n"
        "}\n";

    glsl += functions;

    // shade() dispatcher: sums contributions from all light types
    glsl +=
        "\nvec3 shade(vec3 p, vec3 n, int type, int idx) {\n"
        "    vec3 col = vec3(0.0);\n";
    glsl += shadeBody;
    glsl += "    return col;\n}\n";

    return glsl;
}

void LightingPass::uploadUniforms(unsigned int prog,
                                   const UScene& scene,
                                   const ACamera& /*cam*/) const
{
    using glm::value_ptr;
    GLuint p = static_cast<GLuint>(prog);

    int       nPL = 0;
    glm::vec3 plPos[4], plEffect[4];
    glm::vec3 envEffect(0.0f);

    for (const ALight* light : scene.Lights) {
        if (auto* pl = dynamic_cast<PointLight*>(light->lightComp)) {
            if (nPL >= 4) continue;
            plPos[nPL]    = pl->LightPos;
            plEffect[nPL] = pl->LightColor * pl->LightIntensity;
            ++nPL;
        }
        else if (auto* el = dynamic_cast<EnvironmentLight*>(light->lightComp)) {
            envEffect = el->LightColor * el->LightIntensity;
        }
    }

    glUniform1i(glGetUniformLocation(p, "uNPointLight"), nPL);
    if (nPL > 0) {
        glUniform3fv(glGetUniformLocation(p, "uPLPos"),    nPL, value_ptr(plPos[0]));
        glUniform3fv(glGetUniformLocation(p, "uPLEffect"), nPL, value_ptr(plEffect[0]));
    }
    glUniform3fv(glGetUniformLocation(p, "uEnvEffect"), 1, value_ptr(envEffect));
}

// ===========================================================================
//  URayTracing — GPU renderer methods
// ===========================================================================

URayTracing::URayTracing()  = default;
URayTracing::~URayTracing() = default;

void URayTracing::Init(const UScene& scene)
{
    intersectionPass_ = std::make_unique<IntersectionPass>(scene);
    lightingPass_     = std::make_unique<LightingPass>(scene);

    // Assemble fragment shader:
    //   preamble (version + defines + output + camera uniforms)
    //   IntersectionPass  (geometry uniforms + hit funcs + dispatchers)
    //   LightingPass      (light uniforms + shading funcs + shade())
    //   TRACE_GLSL        (fixed trace loop + main entry)
    std::string fragSrc =
        "#version 330 core\n"
        "#define ENV_LIGHT_SAMPLES "   + std::to_string(ENV_LIGHT_SAMPLES)   + "\n" +
        "#define GI_BOUNCE_DEPTH "     + std::to_string(GI_BOUNCE_DEPTH)     + "\n" +
        "#define SOFT_SHADOW_SAMPLES " + std::to_string(SOFT_SHADOW_SAMPLES) + "\n" +
        "#define MAX_DEPTH 5\n"
        "out vec4 fragColor;\n"
        "uniform vec3  uEye, uU, uV, uW;\n"
        "uniform float uL, uR, uB, uT, uD;\n"
        "uniform int   uWidth, uHeight;\n"
        + intersectionPass_->getGLSL()
        + lightingPass_->getGLSL()
        + TRACE_GLSL;

    GLuint vert = compileShader(GL_VERTEX_SHADER,   VERT_SRC);
    GLuint frag = compileShader(GL_FRAGMENT_SHADER, fragSrc.c_str());
    prog_ = linkProgram(vert, frag);
    glDeleteShader(vert);
    glDeleteShader(frag);

    // Bind the CubeBlock UBO to binding point 0
    GLuint blockIdx = glGetUniformBlockIndex(prog_, "CubeBlock");
    if (blockIdx != GL_INVALID_INDEX)
        glUniformBlockBinding(prog_, blockIdx, 0);

    // Fullscreen quad (NDC triangle pair)
    float quadVerts[] = {
        -1.0f, -1.0f,   1.0f, -1.0f,   1.0f,  1.0f,
        -1.0f, -1.0f,   1.0f,  1.0f,  -1.0f,  1.0f
    };
    glGenVertexArrays(1, &vao_);
    glGenBuffers(1, &vbo_);
    glBindVertexArray(vao_);
    glBindBuffer(GL_ARRAY_BUFFER, vbo_);
    glBufferData(GL_ARRAY_BUFFER, sizeof(quadVerts), quadVerts, GL_STATIC_DRAW);
    glVertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 2 * sizeof(float), (void*)0);
    glEnableVertexAttribArray(0);
    glBindVertexArray(0);

    glUseProgram(prog_);
}

void URayTracing::RenderFrame(const UScene& scene, const ACamera& cam)
{
    uploadCameraUniforms(cam, scene);
    intersectionPass_->uploadUniforms(prog_, scene, cam);
    lightingPass_->uploadUniforms(prog_, scene, cam);

    glClear(GL_COLOR_BUFFER_BIT);
    glBindVertexArray(vao_);
    glDrawArrays(GL_TRIANGLES, 0, 6);
}

void URayTracing::Cleanup()
{
    intersectionPass_.reset();
    lightingPass_.reset();
    glDeleteVertexArrays(1, &vao_);
    glDeleteBuffers(1, &vbo_);
    glDeleteProgram(prog_);
    vao_ = vbo_ = prog_ = 0;
}

void URayTracing::uploadCameraUniforms(const ACamera& cam, const UScene& scene) const
{
    using glm::value_ptr;
    GLuint p = static_cast<GLuint>(prog_);
    glUniform3fv(glGetUniformLocation(p, "uEye"), 1, value_ptr(cam.eye));
    glUniform3fv(glGetUniformLocation(p, "uU"),   1, value_ptr(cam.u));
    glUniform3fv(glGetUniformLocation(p, "uV"),   1, value_ptr(cam.v));
    glUniform3fv(glGetUniformLocation(p, "uW"),   1, value_ptr(cam.w));
    glUniform1f (glGetUniformLocation(p, "uL"),  cam.l);
    glUniform1f (glGetUniformLocation(p, "uR"),  cam.r);
    glUniform1f (glGetUniformLocation(p, "uB"),  cam.b);
    glUniform1f (glGetUniformLocation(p, "uT"),  cam.t);
    glUniform1f (glGetUniformLocation(p, "uD"),  cam.d);
    glUniform1i (glGetUniformLocation(p, "uWidth"),  scene.width);
    glUniform1i (glGetUniformLocation(p, "uHeight"), scene.height);
}

// ===========================================================================
//  CPU ray tracer
//
//  Blinn-Phong model (per lecture):
//    L = ka*Ia + sum_lights[ kd*Il*max(0,n·l) + ks*Il*max(0,n·h)^p ] * (1-shadow)
//  where h = normalize(l + v),  Ia = white (1,1,1) unit ambient.
//
//  mode 0  TraceQ2  Phong + shadow, no reflection
//  mode 1  TraceQ3  Phong + shadow + km mirror reflection (recursive, MAX_DEPTH 5)
//
//  Lights are read from scene.Lights (PointLight components only for Q2/Q3 direct).
//  EnvironmentLight (GI) is handled inside TraceQ3 via ComputePhong → illuminate().
// ===========================================================================

void URayTracing::Render(UScene& scene, ACamera& camera, int mode,
                          const RenderSettings& s) const
{
    scene.outputImage.assign(scene.width * scene.height * 3, 0.0f);

    // ------------------------------------------------------------------
    // Step 1: Trace — one sample or N jittered samples per pixel
    // ------------------------------------------------------------------
    const bool doAA = s.enableAA && s.aaSamples > 1;

    for (int iy = 0; iy < scene.height; ++iy)
        for (int ix = 0; ix < scene.width; ++ix)
        {
            glm::vec3 color;
            if (doAA) {
                color = TracePixelAA(ix, iy, mode, scene, camera, s.aaSamples);
            } else {
                URay ray = camera.generateRay(ix, iy, scene.width, scene.height);
                switch (mode) {
                case 0:  color = TraceQ2(ray, scene, camera); break;
                case 1:  color = TraceQ3(ray, scene, camera); break;
                default: color = glm::vec3(0.0f);
                }
            }
            int idx = (iy * scene.width + ix) * 3;
            scene.outputImage[idx + 0] = color.r;
            scene.outputImage[idx + 1] = color.g;
            scene.outputImage[idx + 2] = color.b;
        }

    // ------------------------------------------------------------------
    // Step 2: Gamma correction  output = linear^(1/gamma)
    // Applied after all pixels are traced so AA averages stay linear.
    // ------------------------------------------------------------------
    if (s.enableGamma)
        ApplyGamma(scene, s.gamma);
}

// ---------------------------------------------------------------------------
//  TracePixelAA — uniform random supersampling (box filter)
//  Shoots N rays with random sub-pixel offsets, returns their average.
//  Thread-local RNG so the same seed gives reproducible results per thread.
// ---------------------------------------------------------------------------
glm::vec3 URayTracing::TracePixelAA(int ix, int iy, int mode,
                                      const UScene& scene, const ACamera& cam,
                                      int N) const
{
    thread_local std::mt19937 rng(std::random_device{}());
    std::uniform_real_distribution<float> dist(0.0f, 1.0f);

    glm::vec3 accum(0.0f);
    for (int s = 0; s < N; ++s) {
        URay ray = cam.generateRayJittered(ix, iy, scene.width, scene.height,
                                            dist(rng), dist(rng));
        glm::vec3 c;
        switch (mode) {
        case 0:  c = TraceQ2(ray, scene, cam); break;
        case 1:  c = TraceQ3(ray, scene, cam); break;
        default: c = glm::vec3(0.0f);
        }
        accum += c;
    }
    return accum / static_cast<float>(N);  // box filter = simple average
}

// ---------------------------------------------------------------------------
//  ApplyGamma — sRGB-style gamma correction applied in-place to outputImage
//  output = clamp(linear, 0, 1) ^ (1/gamma)
// ---------------------------------------------------------------------------
void URayTracing::ApplyGamma(UScene& scene, float gamma) const
{
    const float invGamma = 1.0f / gamma;
    for (float& v : scene.outputImage)
        v = std::pow(glm::clamp(v, 0.0f, 1.0f), invGamma);
}

bool URayTracing::FindClosestHit(const URay& ray, const UScene& scene,
                                  float& outT, const AActor*& outActor) const
{
    outT = FLT_MAX; outActor = nullptr;
    for (const AActor* actor : scene.Actors) {
        float t;
        if (actor->surface->intersect(ray, t) && t < outT)
            { outT = t; outActor = actor; }
    }
    return outActor != nullptr;
}

// ---------------------------------------------------------------------------
//  TraceQ2 — Blinn-Phong + shadow rays, no reflection
//  Reads PointLights from scene.Lights.
//  Ambient: Ia = (1,1,1) white unit intensity (HW3 spec).
// ---------------------------------------------------------------------------
glm::vec3 URayTracing::TraceQ2(const URay& ray, const UScene& scene,
                                const ACamera& camera) const
{
    float t; const AActor* actor;
    if (!FindClosestHit(ray, scene, t, actor)) return glm::vec3(0.0f);

    glm::vec3 p   = ray.origin + t * ray.direction;
    glm::vec3 n   = actor->surface->getNormal(p);
    glm::vec3 v   = glm::normalize(camera.eye - p);
    const Material& mat = actor->surface->material;

    // Ambient: Ia = (1,1,1)
    glm::vec3 color = mat.ka;

    for (const ALight* light : scene.Lights)
    {
        PointLight* pl = dynamic_cast<PointLight*>(light->lightComp);
        if (!pl) continue;  // skip EnvironmentLight for Q2

        glm::vec3 toLight = pl->LightPos - p;
        float     dist    = glm::length(toLight);
        glm::vec3 l       = toLight / dist;

        float NdotL = glm::dot(n, l);
        if (NdotL <= 0.0f) continue;

        // Shadow ray (offset by epsilon along normal to avoid self-intersection)
        URay shadowRay(p + 1e-4f * n, l);
        bool inShadow = false;
        for (const AActor* other : scene.Actors) {
            float st;
            if (other->surface->intersect(shadowRay, st) && st < dist)
                { inShadow = true; break; }
        }
        if (inShadow) continue;

        glm::vec3 Il = pl->LightColor * pl->LightIntensity;

        // Diffuse
        color += mat.kd * Il * NdotL;

        // Specular — Blinn-Phong: h = normalize(l + v)
        if (mat.shininess > 0.0f) {
            glm::vec3 h     = glm::normalize(l + v);
            float     NdotH = glm::max(0.0f, glm::dot(n, h));
            color += mat.ks * Il * glm::pow(NdotH, mat.shininess);
        }
    }

    return glm::clamp(color, 0.0f, 1.0f);
}

// ---------------------------------------------------------------------------
//  TraceQ3 — Q2 + km mirror reflection (recursive up to MAX_DEPTH)
//  Also supports EnvironmentLight GI via ComputePhong → illuminate().
// ---------------------------------------------------------------------------
glm::vec3 URayTracing::TraceQ3(const URay& ray, const UScene& scene,
                                const ACamera& camera, int depth) const
{
    const int MAX_DEPTH = 5;

    auto skyColor = [](const glm::vec3& dir) -> glm::vec3 {
        float t = 0.5f * (glm::normalize(dir).y + 1.0f);
        return glm::mix(glm::vec3(1.0f), glm::vec3(0.5f, 0.7f, 1.0f), t);
    };

    float hitT; const AActor* actor;
    if (!FindClosestHit(ray, scene, hitT, actor)) return skyColor(ray.direction);

    glm::vec3 p = ray.origin + hitT * ray.direction;
    glm::vec3 n = actor->surface->getNormal(p);
    const Material& mat = actor->surface->material;

    // Emissive + Ambient (Ia = (1,1,1))
    glm::vec3 color = mat.emissive + mat.ka;

    // Phong + shadow from all scene lights (PointLight direct + EnvironmentLight GI)
    color += ComputePhong(p, n, actor, ray, scene, camera, depth);

    // Mirror reflection
    glm::vec3 km = mat.km;
    if (depth < MAX_DEPTH && glm::dot(km, km) > 0.0f) {
        glm::vec3 reflDir = glm::reflect(ray.direction, n);
        URay      reflRay(p + 1e-4f * n, reflDir);
        color += km * TraceQ3(reflRay, scene, camera, depth + 1);
    }

    return glm::clamp(color, 0.0f, 1.0f);
}

// ---------------------------------------------------------------------------
//  ComputePhong — sums illuminate() from all lights in scene.Lights
//  (PointLight: Blinn-Phong + soft shadow / EnvironmentLight: GI)
// ---------------------------------------------------------------------------
glm::vec3 URayTracing::ComputePhong(const glm::vec3& p, const glm::vec3& n,
                                     const AActor* actor, const URay& ray,
                                     const UScene& scene, const ACamera& camera,
                                     int depth) const
{
    glm::vec3 color(0.0f);
    for (const ALight* light : scene.Lights)
        color += light->illuminate(p, n, actor, ray, scene, camera, depth, this);
    return color;
}
