<#
.SYNOPSIS
    Create a new OpenGL project that REFERENCES the engine by path
    (instead of copying it). Engine edits in this repo propagate
    immediately to the generated project.

    Unreal-style flow:
       1. GUI folder picker  -> pick parent directory
       2. GUI input box      -> enter project name
       3. Generate <picked>/<name>/ with:
            - <name>.sln, <name>.vcxproj, <name>.vcxproj.filters, main.cpp
            - EngineRoot.props   (absolute path to this engine repo)
            - Package.bat + Package.ps1
            - bin\*.dll          (runtime DLLs copied once)
       4. Generated project compiles directly against this engine repo.

    To make the project fully self-contained for submission,
    double-click Package.bat inside the generated project — it copies
    Engine/, include/, lib/, OpenglViewer.props into the project and
    rewrites EngineRoot.props to use $(SolutionDir).

.NOTES
    Designed to be launched by GenerateProject.bat from the repo root.
    Requires Windows PowerShell (uses System.Windows.Forms).
#>

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing
Add-Type -AssemblyName Microsoft.VisualBasic

# ── Locate engine root (parent of Scripts\) ───────────────────────────────────
$EngineRoot  = Split-Path -Parent $PSScriptRoot
$TemplateDir = Join-Path $EngineRoot 'Template'

if (-not (Test-Path (Join-Path $TemplateDir 'Template.vcxproj'))) {
    [System.Windows.Forms.MessageBox]::Show(
        "Cannot find Template\Template.vcxproj at:`n$TemplateDir",
        'Project Generator', 'OK', 'Error') | Out-Null
    return
}

Write-Host ''
Write-Host '  MyFirstGameEngine - Project Generator (linked mode)' -ForegroundColor Cyan
Write-Host '  ===================================================' -ForegroundColor Cyan
Write-Host ''

# ── [1/4] Pick parent folder ──────────────────────────────────────────────────
Write-Host '  [1/4] Choose a parent folder for the new project...' -ForegroundColor Yellow

$dialog = New-Object System.Windows.Forms.FolderBrowserDialog
$dialog.Description = 'Select a parent folder. A new sub-folder will be created inside it for your project.'
$dialog.ShowNewFolderButton = $true
$dialog.SelectedPath = [Environment]::GetFolderPath('Desktop')

if ($dialog.ShowDialog() -ne [System.Windows.Forms.DialogResult]::OK) {
    Write-Host '  Cancelled.' -ForegroundColor DarkGray
    return
}
$parent = $dialog.SelectedPath
Write-Host "        $parent" -ForegroundColor DarkGray

# ── [2/4] Ask for project name ────────────────────────────────────────────────
Write-Host '  [2/4] Enter a project name...' -ForegroundColor Yellow

$name = [Microsoft.VisualBasic.Interaction]::InputBox(
    "Enter the project name.`r`n`r`nIt will be used as the sub-folder name and the .sln / .vcxproj name.`r`nAllowed: letters, digits, underscore. Must not start with a digit.",
    'Project name',
    'MyProject')

if ([string]::IsNullOrWhiteSpace($name)) {
    Write-Host '  Cancelled.' -ForegroundColor DarkGray
    return
}

$name = $name.Trim()
if ($name -notmatch '^[A-Za-z_][A-Za-z0-9_]*$') {
    [System.Windows.Forms.MessageBox]::Show(
        "Invalid project name: '$name'`n`nUse letters, digits, underscore. Must not start with a digit.",
        'Project Generator', 'OK', 'Error') | Out-Null
    return
}

$dest = Join-Path $parent $name
if (Test-Path $dest) {
    [System.Windows.Forms.MessageBox]::Show(
        "Destination already exists:`n$dest`n`nPick a different name or delete the existing folder.",
        'Project Generator', 'OK', 'Error') | Out-Null
    return
}

Write-Host "        $name  ->  $dest" -ForegroundColor DarkGray

# ── [3/4] Generate project + link to engine ──────────────────────────────────
Write-Host '  [3/4] Generating project files...' -ForegroundColor Yellow
New-Item -ItemType Directory -Path $dest | Out-Null

# bin\ DLLs are runtime dependencies of the exe. Copy them once so the
# generated project's bin\ has them next to the future exe.
$binSrc = Join-Path $EngineRoot 'bin'
if (Test-Path $binSrc) {
    Write-Host '        copy bin\ (runtime DLLs)' -ForegroundColor DarkGray
    New-Item -ItemType Directory -Path (Join-Path $dest 'bin') | Out-Null
    Get-ChildItem -Path $binSrc -Filter '*.dll' -File |
        Copy-Item -Destination (Join-Path $dest 'bin') -Force
}

# EngineRoot.props with absolute path to this engine repo.
# Trailing backslash so $(EngineRootDir)Engine\... concatenates cleanly.
$engineRootForProps = $EngineRoot
if (-not $engineRootForProps.EndsWith('\')) { $engineRootForProps += '\' }

$propsXml = @"
<?xml version="1.0" encoding="utf-8"?>
<!--
    EngineRoot.props - generated by GenerateProject (linked mode).
    Points at the original engine repo so engine edits propagate here.
    Run Package.bat to convert this project to a self-contained copy.
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="UserMacros">
    <EngineRootDir>$engineRootForProps</EngineRootDir>
  </PropertyGroup>
  <ItemGroup>
    <BuildMacro Include="EngineRootDir">
      <Value>`$(EngineRootDir)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>
"@

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $dest 'EngineRoot.props'), $propsXml, $utf8NoBom)
Write-Host "        write EngineRoot.props  (-> $engineRootForProps)" -ForegroundColor DarkGray

# Patch GUID + RootNamespace into a copy of Template.vcxproj.
$projGuid     = [System.Guid]::NewGuid().ToString().ToUpper()
$slnGuid      = [System.Guid]::NewGuid().ToString().ToUpper()
$projTypeGuid = '8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942'

$vcxSrc = Join-Path $TemplateDir 'Template.vcxproj'
$vcxDst = Join-Path $dest "$name.vcxproj"
(Get-Content $vcxSrc -Raw -Encoding UTF8) `
    -replace 'AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE', $projGuid `
    -replace '<RootNamespace>Template</RootNamespace>', "<RootNamespace>$name</RootNamespace>" |
    Set-Content $vcxDst -Encoding UTF8

# Filters file has no GUID / name to patch.
Copy-Item (Join-Path $TemplateDir 'Template.vcxproj.filters') (Join-Path $dest "$name.vcxproj.filters")

# main.cpp stub.
Copy-Item (Join-Path $TemplateDir 'main.cpp') (Join-Path $dest 'main.cpp')

# Package.bat + Package.ps1 (lets the user freeze the engine into the project later).
Copy-Item (Join-Path $TemplateDir 'Package.bat') (Join-Path $dest 'Package.bat')
Copy-Item (Join-Path $TemplateDir 'Package.ps1') (Join-Path $dest 'Package.ps1')

# ── [4/4] .sln ────────────────────────────────────────────────────────────────
Write-Host '  [4/4] Writing solution file...' -ForegroundColor Yellow

$slnLines = @(
    'Microsoft Visual Studio Solution File, Format Version 12.00'
    '# Visual Studio Version 17'
    'VisualStudioVersion = 17.0.31903.59'
    'MinimumVisualStudioVersion = 10.0.40219.1'
    "Project(`"{$projTypeGuid}`") = `"$name`", `"$name.vcxproj`", `"{$projGuid}`""
    'EndProject'
    'Global'
    "`tGlobalSection(SolutionConfigurationPlatforms) = preSolution"
    "`t`tDebug|Win32 = Debug|Win32"
    "`t`tRelease|Win32 = Release|Win32"
    "`tEndGlobalSection"
    "`tGlobalSection(ProjectConfigurationPlatforms) = postSolution"
    "`t`t{$projGuid}.Debug|Win32.ActiveCfg = Debug|Win32"
    "`t`t{$projGuid}.Debug|Win32.Build.0 = Debug|Win32"
    "`t`t{$projGuid}.Release|Win32.ActiveCfg = Release|Win32"
    "`t`t{$projGuid}.Release|Win32.Build.0 = Release|Win32"
    "`tEndGlobalSection"
    "`tGlobalSection(SolutionProperties) = preSolution"
    "`t`tHideSolutionNode = FALSE"
    "`tEndGlobalSection"
    "`tGlobalSection(ExtensibilityGlobals) = postSolution"
    "`t`tSolutionGuid = {$slnGuid}"
    "`tEndGlobalSection"
    'EndGlobal'
)

[System.IO.File]::WriteAllLines((Join-Path $dest "$name.sln"), $slnLines, $utf8NoBom)

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host ''
Write-Host '  Done!' -ForegroundColor Green
Write-Host "  $dest" -ForegroundColor Green
Write-Host "    $name.sln"
Write-Host "    $name.vcxproj"
Write-Host "    $name.vcxproj.filters"
Write-Host '    EngineRoot.props   (linked -> engine repo)'
Write-Host '    main.cpp'
Write-Host '    Package.bat / Package.ps1   (run to freeze engine into project)'
Write-Host '    bin\               (runtime DLLs)'
Write-Host ''
Write-Host '  Engine source stays in the original repo.' -ForegroundColor DarkGray
Write-Host '  Edit Engine\... there and rebuild this project to pick up changes.' -ForegroundColor DarkGray
Write-Host ''

$openIt = [System.Windows.Forms.MessageBox]::Show(
    "Project created (linked mode):`n$dest`n`nOpen $name.sln in Visual Studio now?",
    'Project Generator',
    'YesNo', 'Information')

if ($openIt -eq [System.Windows.Forms.DialogResult]::Yes) {
    Start-Process (Join-Path $dest "$name.sln")
}
